services:
  obscura:
    image: h4ckf0r0day/obscura:latest
    container_name: obscura
    restart: unless-stopped

    ports:
      - "127.0.0.1:9222:9222"

    volumes:
      - ./output:/output

    command:
      - serve
      - --port
      - "9222"
      - --host
      - "0.0.0.0"