run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - revive
    - gosec
    - bodyclose
    - noctx
    - misspell
    - unconvert
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  revive:
    confidence: 0.8
    rules:
      - name: exported
      - name: indent-error-flow
      - name: unused-parameter
