services:
  web:
    build:
      args:
        NEXT_PUBLIC_APP_URL: http://localhost:30006
        NEXT_PUBLIC_SITE_URL: http://localhost:30005
        NEXT_PUBLIC_WEB_URL: http://localhost:30005
    environment:
      NEXT_PUBLIC_APP_URL: http://localhost:30006
      NEXT_PUBLIC_SITE_URL: http://localhost:30005
      NEXT_PUBLIC_WEB_URL: http://localhost:30005
    ports:
      - "127.0.0.1:30005:3000"

  app:
    build:
      args:
        VITE_WEB_AUTH_URL: http://localhost:30005/auth
    environment:
      WEB_AUTH_URL: http://localhost:30005/auth
    ports:
      - "127.0.0.1:30006:8080"

  api-gateway:
    environment:
      CORS_ALLOWED_ORIGINS: http://localhost:30005,http://localhost:30006

  auth-service:
    environment:
      APP_RETURN_URL: http://localhost:30006/
      ALLOWED_ORIGIN: http://localhost:30005

  organizations-service:
    environment:
      APP_BASE_URL: http://localhost:30006
      INVITATION_LOGIN_URL: http://localhost:30005/auth

  ia-service:
    environment:
      IA_PROVIDER_HTTP_REFERER: http://localhost:30006

  kratos-migrate:
    environment:
      WEB_PUBLIC_URL: http://localhost:30005
      APP_PUBLIC_URL: http://localhost:30006
      DOC_PUBLIC_URL: http://localhost:30001
      WEB_AUTH_URL: http://localhost:30005/auth

  kratos:
    environment:
      WEB_PUBLIC_URL: http://localhost:30005
      APP_PUBLIC_URL: http://localhost:30006
      DOC_PUBLIC_URL: http://localhost:30001
      WEB_AUTH_URL: http://localhost:30005/auth
