FROM golang:1.26.0-alpine3.23 AS dev

WORKDIR /workspace

RUN apk --no-cache add git && go install github.com/air-verse/air@latest

COPY go.work go.mod ./
COPY services ./services

RUN go work sync

CMD ["air", "-v"]
