import { PromptItem, Stage } from "./types";
import { normalizeModelName, parseRelativeTimeToMinutes } from "./prompts-workspace-utils";

type DashboardPromptInput = {
  text: string;
  model: string;
  time: string;
  mention: boolean;
  rank: number | null;
  score: number;
  persona: string;
  competitorsMentioned: string[];
};

type DashboardCompetitor = {
  name: string;
};

type BuildDashboardPromptsParams = {
  recentPrompts: DashboardPromptInput[];
  competitors: DashboardCompetitor[];
  availableModels: string[];
  stages: Stage[];
};

export function buildDashboardPrompts({
  recentPrompts,
  competitors,
  availableModels,
  stages,
}: BuildDashboardPromptsParams): PromptItem[] {
  return recentPrompts.map((item, index) => {
    const stage = stages[index % stages.length];
    const normalizedModel = normalizeModelName(item.model);
    const knownModel =
      availableModels.find((model) => normalizeModelName(model) === normalizedModel) ||
      availableModels.find((model) => normalizedModel.includes(normalizeModelName(model).split(" ")[0])) ||
      item.model;
    const minutes = parseRelativeTimeToMinutes(item.time);
    const score = Math.max(0, Math.min(100, item.score ?? 0));
    const mentionRate = item.mention ? Math.max(55, score) : Math.min(45, score);
    const rank = item.rank ?? 9.9;
    const trend30d = [score * 0.45, score * 0.55, score * 0.65, score * 0.8, score * 0.88, score * 0.94, score].map((point) =>
      Math.max(8, Math.round(point)),
    );

    return {
      id: `live-${index + 1}`,
      prompt: item.text,
      type: item.rank && item.rank <= 2 ? "Comparison" : "Use case",
      stage,
      persona: item.persona,
      models: [knownModel],
      mentionRate,
      rank,
      sov: Math.max(5, Math.min(95, score - 12)),
      lastRunMinutes: minutes,
      trend30d,
      status: "active",
      runs: [
        {
          id: `run-live-${index + 1}`,
          time: item.time,
          model: knownModel,
          minutesAgo: minutes,
          mention: item.mention,
          rank: item.rank,
          competitor: item.competitorsMentioned[0] || competitors[0]?.name || "Competitor",
          score,
          error: item.mention ? null : "No mention",
          critical: !item.mention && score <= 25,
          response: `Live dashboard response snapshot for "${item.text}".`,
          highlights: [
            item.mention ? "Brand mention detected" : "Brand mention missing",
            item.rank ? `Ranked #${item.rank}` : "No rank available",
            `Visibility score ${score}`,
          ],
        },
      ],
    };
  });
}

export function buildAutoGeneratedPrompts(availableModels: string[], availablePersonas: string[], stages: Stage[]): PromptItem[] {
  const topics = [
    "startup CRM",
    "sales pipeline",
    "onboarding flow",
    "pricing page",
    "SMB conversion",
    "B2B integrations",
    "security compliance",
    "customer success",
    "sales enablement",
    "lead scoring",
  ];
  const modelPool = availableModels.length > 0 ? availableModels : ["ChatGPT"];
  const personaPool = availablePersonas.length > 0 ? availablePersonas : ["General"];

  return Array.from({ length: 50 }).map((_, index) => {
    const topic = topics[index % topics.length];
    const id = `auto-${Date.now()}-${index}`;
    const model = modelPool[index % modelPool.length];
    const stage = stages[index % stages.length];
    const personaValue = personaPool[index % personaPool.length];
    return {
      id,
      prompt: `Auto ${index + 1}: Best ${topic} strategy for ${personaValue}?`,
      type: "Generated",
      stage,
      persona: personaValue,
      models: [model],
      mentionRate: Math.max(5, 70 - index),
      rank: 1 + (index % 6) * 0.7,
      sov: Math.max(4, 38 - (index % 10)),
      lastRunMinutes: 15 + index * 8,
      trend30d: [8, 11, 15, 19, 24, 28, 31],
      status: "active",
      runs: [],
    };
  });
}

export function buildImportedPrompts(): PromptItem[] {
  return [
    {
      id: `csv-${Date.now()}-1`,
      prompt: "CRM tool for agencies with multi-brand reporting",
      type: "CSV import",
      stage: "Consideration",
      persona: "CMO",
      models: ["ChatGPT", "Perplexity"],
      mentionRate: 51,
      rank: 2.4,
      sov: 34,
      lastRunMinutes: 40,
      trend30d: [28, 31, 33, 39, 43, 47, 51],
      status: "active",
      runs: [],
    },
    {
      id: `csv-${Date.now()}-2`,
      prompt: "Best pipeline CRM with SOC2 and SSO",
      type: "CSV import",
      stage: "Decision",
      persona: "CTO",
      models: ["Claude", "Gemini"],
      mentionRate: 62,
      rank: 1.7,
      sov: 45,
      lastRunMinutes: 80,
      trend30d: [31, 36, 40, 42, 47, 54, 62],
      status: "active",
      runs: [],
    },
  ];
}
