"use client";

import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CreatePromptDialog } from "./create-prompt-dialog";
import { PromptDetailsSheet } from "./prompt-details-sheet";
import { PromptsFiltersToolbar } from "./prompts-filters-toolbar";
import { PromptsPageHeader } from "./prompts-page-header";
import { PromptsTabContent } from "./prompts-tab-content";
import { ResponseDetailsSheet } from "./response-details-sheet";
import { ResponsesTabContent } from "./responses-tab-content";
import { rankTone, STAGES, statusBadgeVariant, truncate } from "./prompts-workspace-utils";
import { usePromptsResponsesState } from "./use-prompts-responses-state";
import { PeriodKey, Persona, PromptSort, ResponseView, Stage } from "./types";

export function PromptsResponsesWorkspace() {
  const state = usePromptsResponsesState();

  return (
    <div className="h-full min-h-0 overflow-hidden p-2 md:p-4">
      <div className="flex h-full min-h-0 flex-col rounded-md bg-background">
        <div className="border-b p-3 md:p-4">
          <PromptsPageHeader
            activeCount={state.prompts.filter((item) => item.status === "active").length}
            isDemo={state.mode === "demo"}
            onNewPrompt={() => state.setIsCreateOpen(true)}
            onAutoGenerate={state.addAutoGeneratedPrompts}
            onImportCsv={state.addImportedPrompts}
          />

          <PromptsFiltersToolbar
            period={state.period}
            setPeriod={(value) => state.setPeriod(value as PeriodKey)}
            dateRange={state.dateRange}
            setDateRange={state.setDateRange}
            persona={state.persona}
            setPersona={(value) => state.setPersona(value as "all" | Persona)}
            availablePersonas={state.availablePersonas}
            search={state.search}
            setSearch={state.setSearch}
            hasActiveGlobalFilters={state.hasActiveGlobalFilters}
            clearFilters={state.clearFilters}
            activeStages={state.activeStages}
            stages={STAGES}
            toggleStage={(stage) => state.toggleStage(stage as Stage)}
            modelsPopoverOpen={state.modelsPopoverOpen}
            setModelsPopoverOpen={state.setModelsPopoverOpen}
            allModelsSelected={state.allModelsSelected}
            selectedModels={state.selectedModels}
            availableModels={state.availableModels}
            getModelVisual={state.getModelVisual}
            toggleModel={state.toggleModel}
          />
        </div>

        <Tabs value={state.tab} onValueChange={(value) => state.setTab(value as "prompts" | "responses")} className="flex min-h-0 flex-1 flex-col">
          <div className="border-b px-4 py-3 md:px-6">
            <TabsList>
              <TabsTrigger value="prompts">Prompts</TabsTrigger>
              <TabsTrigger value="responses">Responses</TabsTrigger>
            </TabsList>
          </div>

          <TabsContent value="prompts" className="m-0 flex min-h-0 flex-1">
            <PromptsTabContent
              filteredPrompts={state.filteredPrompts}
              selectedPromptIds={state.selectedPromptIds}
              selectedPrompt={state.selectedPrompt}
              promptSort={state.promptSort}
              setPromptSort={(value) => state.setPromptSort(value as PromptSort)}
              toggleSelectAllPrompts={state.toggleSelectAllPrompts}
              togglePromptSelection={state.togglePromptSelection}
              setSelectedPromptId={state.setSelectedPromptId}
              setIsPromptDetailsOpen={state.setIsPromptDetailsOpen}
              applyBulkStatus={state.applyBulkStatus}
              setFocusPromptId={state.setFocusPromptId}
              setTabResponses={() => state.setTab("responses")}
              deletePrompt={state.deletePrompt}
              getModelVisual={state.getModelVisual}
              rankTone={rankTone}
              statusBadgeVariant={statusBadgeVariant}
              onRunSelect={state.setSelectedResponseId}
            />
          </TabsContent>

          <TabsContent value="responses" className="m-0 flex min-h-0 flex-1 flex-col">
            <ResponsesTabContent
              onlyErrors={state.onlyErrors}
              setOnlyErrors={state.setOnlyErrors}
              criticalOnly={state.criticalOnly}
              setCriticalOnly={state.setCriticalOnly}
              noMentionOnly={state.noMentionOnly}
              setNoMentionOnly={state.setNoMentionOnly}
              topCompetitor={state.topCompetitor}
              setTopCompetitor={state.setTopCompetitor}
              availableCompetitors={state.availableCompetitors}
              viewMode={state.viewMode}
              setViewMode={(value) => state.setViewMode(value as ResponseView)}
              filteredResponses={state.filteredResponses}
              setSelectedResponseId={state.setSelectedResponseId}
              getModelVisual={state.getModelVisual}
              rankTone={rankTone}
              truncate={truncate}
            />
          </TabsContent>
        </Tabs>
      </div>

      <CreatePromptDialog
        open={state.isCreateOpen}
        onOpenChange={state.setIsCreateOpen}
        formPrompt={state.formPrompt}
        setFormPrompt={state.setFormPrompt}
        formType={state.formType}
        setFormType={state.setFormType}
        formPersona={state.formPersona}
        setFormPersona={state.setFormPersona}
        formModel={state.formModel}
        setFormModel={state.setFormModel}
        availablePersonas={state.availablePersonas}
        availableModels={state.availableModels}
        getModelLabel={(model) => state.getModelVisual(model).label}
        onCreate={state.createPrompt}
      />

      <PromptDetailsSheet
        open={state.isPromptDetailsOpen}
        onOpenChange={state.setIsPromptDetailsOpen}
        prompt={state.selectedPrompt}
      />

      <ResponseDetailsSheet
        response={state.selectedResponse}
        onOpenChange={(open) => !open && state.setSelectedResponseId(null)}
      />
    </div>
  );
}
