"use client";
import { useEffect, useMemo, useState } from "react";
import { DateRange } from "react-day-picker";
import { differenceInCalendarDays } from "date-fns";
import { useDashboardData } from "@/hooks/use-dashboard-data";
import {
  PERIOD_TO_MINUTES,
  STAGES,
  normalizeModelName,
} from "./prompts-workspace-utils";
import { AIModel, ModelVisual, PeriodKey, Persona, PromptItem, PromptSort, ResponseView, Stage } from "./types";
import { buildAutoGeneratedPrompts, buildDashboardPrompts, buildImportedPrompts } from "./prompt-data-factory";
export function usePromptsResponsesState() {
  const { data: dashboardData, mode } = useDashboardData();
  const liveModels = useMemo(() => dashboardData.models.filter((item) => item.live), [dashboardData.models]);
  const modelMeta = useMemo(() => {
    const map = new Map<string, { icon: string; description: string; label: string }>();
    for (const model of liveModels) {
      const key = normalizeModelName(model.name);
      map.set(key, {
        icon: model.icon,
        description: model.description,
        label: model.name,
      });
      if (key.includes("perplexity")) map.set("perplexity", { icon: model.icon, description: model.description, label: model.name });
      if (key.includes("claude")) map.set("claude", { icon: model.icon, description: model.description, label: model.name });
      if (key.includes("chatgpt")) map.set("chatgpt", { icon: model.icon, description: model.description, label: model.name });
      if (key.includes("gemini")) map.set("gemini", { icon: model.icon, description: model.description, label: model.name });
      if (key.includes("google")) map.set("google", { icon: model.icon, description: model.description, label: model.name });
    }
    return map;
  }, [liveModels]);

  const getModelVisual = (model: string): ModelVisual =>
    modelMeta.get(normalizeModelName(model)) || {
      icon: "/models/openai.svg",
      description: "AI model",
      label: model,
    };

  const availableModels = useMemo(() => liveModels.map((item) => item.name), [liveModels]);
  const availablePersonas = useMemo(
    () => Array.from(new Set(dashboardData.recent_prompts.map((item) => item.persona))),
    [dashboardData.recent_prompts],
  );
  const availableCompetitors = useMemo(
    () => dashboardData.project.competitors.map((item) => item.name),
    [dashboardData.project.competitors],
  );

  const dashboardPrompts = useMemo<PromptItem[]>(
    () =>
      buildDashboardPrompts({
        recentPrompts: dashboardData.recent_prompts,
        competitors: dashboardData.project.competitors,
        availableModels,
        stages: STAGES,
      }),
    [availableModels, dashboardData.project.competitors, dashboardData.recent_prompts],
  );

  const [period, setPeriod] = useState<PeriodKey>("7d");
  const [dateRange, setDateRange] = useState<DateRange | undefined>(undefined);
  const [tab, setTab] = useState<"prompts" | "responses">("prompts");
  const [persona, setPersona] = useState<"all" | Persona>("all");
  const [search, setSearch] = useState("");
  const [activeStages, setActiveStages] = useState<Stage[]>([]);
  const [selectedModels, setSelectedModels] = useState<AIModel[]>([]);
  const [promptSort, setPromptSort] = useState<PromptSort>("mention");
  const [viewMode, setViewMode] = useState<ResponseView>("table");
  const [onlyErrors, setOnlyErrors] = useState(false);
  const [criticalOnly, setCriticalOnly] = useState(false);
  const [noMentionOnly, setNoMentionOnly] = useState(false);
  const [topCompetitor, setTopCompetitor] = useState<"all" | string>("all");
  const [selectedPromptIds, setSelectedPromptIds] = useState<string[]>([]);
  const [selectedPromptId, setSelectedPromptId] = useState<string | null>(null);
  const [isPromptDetailsOpen, setIsPromptDetailsOpen] = useState(false);
  const [selectedResponseId, setSelectedResponseId] = useState<string | null>(null);
  const [focusPromptId, setFocusPromptId] = useState<string | null>(null);
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [prompts, setPrompts] = useState<PromptItem[]>([]);
  const [formPrompt, setFormPrompt] = useState("");
  const [formType, setFormType] = useState("Awareness");
  const [formPersona, setFormPersona] = useState<Persona>("CTO");
  const [formModel, setFormModel] = useState<AIModel>("ChatGPT");
  const [modelsPopoverOpen, setModelsPopoverOpen] = useState(false);

  useEffect(() => {
    setPrompts(dashboardPrompts);
    setSelectedPromptId((current) => current ?? dashboardPrompts[0]?.id ?? null);
  }, [dashboardPrompts]);

  useEffect(() => {
    if (availableModels.length === 0) return;
    setSelectedModels((current) => {
      const kept = current.filter((model) => availableModels.includes(model));
      if (kept.length > 0) return kept;
      return availableModels;
    });
    setFormModel((current) => (availableModels.includes(current) ? current : availableModels[0]));
    setFormPersona((current) => (availablePersonas.includes(current) ? current : availablePersonas[0] || current));
  }, [availableModels, availablePersonas]);

  const allResponses = useMemo(() => prompts.flatMap((prompt) => prompt.runs.map((run) => ({ ...run, promptId: prompt.id, prompt: prompt.prompt, stage: prompt.stage, persona: prompt.persona, models: prompt.models }))), [prompts]);
  const rangeMinutes = useMemo(() => {
    if (period !== "custom") return PERIOD_TO_MINUTES[period];
    if (!dateRange?.from) return PERIOD_TO_MINUTES["90d"];
    const to = dateRange.to ?? dateRange.from;
    const days = Math.max(1, differenceInCalendarDays(to, dateRange.from) + 1);
    return days * 24 * 60;
  }, [dateRange, period]);

  const filteredPrompts = useMemo(() => {
    const searchLower = search.toLowerCase().trim();
    const rows = prompts.filter((item) => {
      const matchesPeriod = item.lastRunMinutes <= rangeMinutes;
      const matchesModel = selectedModels.length === 0 || item.models.some((model) => selectedModels.includes(model));
      const matchesPersona = persona === "all" || item.persona === persona;
      const matchesStage = activeStages.length === 0 || activeStages.includes(item.stage);
      const matchesSearch = searchLower.length === 0 || item.prompt.toLowerCase().includes(searchLower);
      return matchesPeriod && matchesModel && matchesPersona && matchesStage && matchesSearch;
    });

    return rows.sort((a, b) => {
      if (promptSort === "rank") return a.rank - b.rank;
      if (promptSort === "sov") return b.sov - a.sov;
      return b.mentionRate - a.mentionRate;
    });
  }, [activeStages, persona, promptSort, prompts, rangeMinutes, search, selectedModels]);
  const filteredResponses = useMemo(() => {
    const searchLower = search.toLowerCase().trim();
    return allResponses
      .filter((item) => {
        const matchesPeriod = item.minutesAgo <= rangeMinutes;
        const matchesModel = selectedModels.length === 0 || selectedModels.includes(item.model);
        const matchesPersona = persona === "all" || item.persona === persona;
        const matchesStage = activeStages.length === 0 || activeStages.includes(item.stage);
        const matchesSearch = searchLower.length === 0 || item.prompt.toLowerCase().includes(searchLower);
        const matchesError = !onlyErrors || Boolean(item.error);
        const matchesCritical = !criticalOnly || item.critical;
        const matchesNoMention = !noMentionOnly || !item.mention;
        const matchesCompetitor = topCompetitor === "all" || item.competitor === topCompetitor;
        const matchesFocusedPrompt = !focusPromptId || item.promptId === focusPromptId;
        return (
          matchesPeriod &&
          matchesModel &&
          matchesPersona &&
          matchesStage &&
          matchesSearch &&
          matchesError &&
          matchesCritical &&
          matchesNoMention &&
          matchesCompetitor &&
          matchesFocusedPrompt
        );
      })
      .sort((a, b) => a.minutesAgo - b.minutesAgo);
  }, [
    activeStages,
    allResponses,
    criticalOnly,
    focusPromptId,
    noMentionOnly,
    onlyErrors,
    rangeMinutes,
    persona,
    search,
    selectedModels,
    topCompetitor,
  ]);

  const selectedPrompt = prompts.find((item) => item.id === selectedPromptId) ?? null;
  const selectedResponse = allResponses.find((item) => item.id === selectedResponseId) ?? null;
  const allModelsSelected =
    availableModels.length > 0 &&
    selectedModels.length === availableModels.length &&
    availableModels.every((model) => selectedModels.includes(model));

  const hasActiveGlobalFilters =
    period !== "7d" ||
    persona !== "all" ||
    activeStages.length > 0 ||
    search.trim().length > 0 ||
    selectedModels.length !== availableModels.length ||
    availableModels.some((model) => !selectedModels.includes(model));

  const clearFilters = () => {
    setPeriod("7d");
    setDateRange(undefined);
    setSelectedModels(availableModels);
    setPersona("all");
    setActiveStages([]);
    setSearch("");
    setOnlyErrors(false);
    setCriticalOnly(false);
    setNoMentionOnly(false);
    setTopCompetitor("all");
    setFocusPromptId(null);
  };

  const toggleModel = (model: AIModel) => {
    if (allModelsSelected) {
      setSelectedModels([model]);
      return;
    }
    setSelectedModels((prev) => (prev.includes(model) ? prev.filter((item) => item !== model) : [...prev, model]));
  };

  const toggleStage = (stage: Stage) => {
    setActiveStages((prev) => (prev.includes(stage) ? prev.filter((item) => item !== stage) : [...prev, stage]));
  };

  const togglePromptSelection = (id: string) => {
    setSelectedPromptIds((prev) => (prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]));
  };

  const toggleSelectAllPrompts = (checked: boolean) => {
    if (!checked) {
      setSelectedPromptIds([]);
      return;
    }
    setSelectedPromptIds(filteredPrompts.map((item) => item.id));
  };

  const applyBulkStatus = (status: PromptItem["status"]) => {
    if (selectedPromptIds.length === 0) return;
    setPrompts((prev) => prev.map((item) => (selectedPromptIds.includes(item.id) ? { ...item, status } : item)));
  };

  const createPrompt = () => {
    if (!formPrompt.trim()) return;
    const nextId = `p${prompts.length + 1}`;
    const newPrompt: PromptItem = {
      id: nextId,
      prompt: formPrompt.trim(),
      type: formType,
      stage: "Awareness",
      persona: formPersona,
      models: [formModel],
      mentionRate: 0,
      rank: 9.9,
      sov: 0,
      lastRunMinutes: 1,
      trend30d: [0, 0, 0, 0, 0, 0, 0],
      status: "active",
      runs: [],
    };
    setPrompts((prev) => [newPrompt, ...prev]);
    setFormPrompt("");
    setFormType("Awareness");
    setFormPersona(availablePersonas[0] || "General");
    setFormModel(availableModels[0] || "ChatGPT");
    setIsCreateOpen(false);
  };

  const addAutoGeneratedPrompts = () => setPrompts((prev) => [...buildAutoGeneratedPrompts(availableModels, availablePersonas, STAGES), ...prev]);
  const addImportedPrompts = () => {
    const imported = buildImportedPrompts();
    setPrompts((prev) => [...imported, ...prev]);
  };

  const deletePrompt = (id: string) => {
    setPrompts((prev) => prev.filter((item) => item.id !== id));
    setSelectedPromptIds((prev) => prev.filter((item) => item !== id));
    if (selectedPromptId === id) setSelectedPromptId(null);
  };

  return {
    mode,
    tab,
    setTab,
    prompts,
    filteredPrompts,
    filteredResponses,
    selectedPrompt,
    selectedResponse,
    selectedPromptIds,
    setSelectedPromptId,
    setSelectedResponseId,
    isPromptDetailsOpen,
    setIsPromptDetailsOpen,
    period,
    setPeriod,
    dateRange,
    setDateRange,
    persona,
    setPersona,
    availablePersonas,
    search,
    setSearch,
    activeStages,
    setActiveStages,
    selectedModels,
    availableModels,
    allModelsSelected,
    modelsPopoverOpen,
    setModelsPopoverOpen,
    hasActiveGlobalFilters,
    clearFilters,
    toggleModel,
    toggleStage,
    promptSort,
    setPromptSort,
    toggleSelectAllPrompts,
    togglePromptSelection,
    applyBulkStatus,
    setFocusPromptId,
    deletePrompt,
    viewMode,
    setViewMode,
    onlyErrors,
    setOnlyErrors,
    criticalOnly,
    setCriticalOnly,
    noMentionOnly,
    setNoMentionOnly,
    topCompetitor,
    setTopCompetitor,
    availableCompetitors,
    isCreateOpen,
    setIsCreateOpen,
    formPrompt,
    setFormPrompt,
    formType,
    setFormType,
    formPersona,
    setFormPersona,
    formModel,
    setFormModel,
    createPrompt,
    addAutoGeneratedPrompts,
    addImportedPrompts,
    getModelVisual,
  };
}
