import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import localFont from "next/font/local";
import { ReferralTracker } from "@/components/referral-tracker";
import { CookieBanner } from "@/components/cookie-banner";
import { Suspense, type ReactNode } from "react";
import { IntlayerClientProvider } from "next-intlayer";

const Lena = localFont({
  src: "./font/Lena.ttf",
  display: "swap",
  variable: "--font-lena",
});

const MulishFont = localFont({
  src: "./font/Mulish.woff2",
  display: "swap",
  weight: "200 1000",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="fr">
      <body
        className={`${Lena.variable} ${MulishFont.className} antialiased min-h-screen bg-gray-50`}
      >
        <div className="min-h-screen flex flex-col">
          <Suspense fallback={null}>
            <ReferralTracker />
          </Suspense>
          <IntlayerClientProvider locale="fr">
            <Providers>{children}</Providers>
          </IntlayerClientProvider>
          <Suspense fallback={null}>
            <CookieBanner />
          </Suspense>
        </div>
      </body>
    </html>
  );
}
