apiVersion: v1
kind: Service
metadata:
  name: permission-service
  labels:
    app: permission-service
spec:
  type: ClusterIP
  selector:
    app: permission-service
  ports:
    - name: http
      port: 8085
      targetPort: http
