"use client";

import { useDeferredValue, useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { DateRange } from "react-day-picker";
import { differenceInCalendarDays } from "date-fns";
import { useMonitoringData } from "@/hooks/use-monitoring-data";
import { apiRoutes } from "@/lib/api-config";
import { appQueryKeys } from "@/lib/query-keys";
import { toSafeImageAssetPath } from "@/lib/safe-asset-path";
import { gatewayJSON } from "@/shared/api/gateway";
import { SELECTED_ORG_KEY } from "@/features/models/core/model-access";
import {
  DEFAULT_PROMPT_CRON,
  DEFAULT_PROMPT_TIMEZONE,
  PERIOD_TO_MINUTES,
  STAGES,
  defaultPromptSchedule,
  normalizeModelName,
  promptScheduleLabel,
} from "./prompts-workspace-utils";
import {
  AIModel,
  ModelVisual,
  PeriodKey,
  Persona,
  PromptItem,
  PromptRowMode,
  PromptSchedule,
  PromptSort,
  PromptSortDirection,
  ResponseView,
} from "./types";
import {
  buildAutoGeneratedPrompts,
  buildImportedPrompts,
  buildPromptPageItems,
  buildResponseRows,
} from "./prompt-data-factory";

const PROMPTS_PAGE_SIZE = 25;
const PROMPTS_CATALOG_PAGE_SIZE = 100;
const RESPONSES_BATCH_SIZE = 40;

const PROMPT_SORT_DEFAULT_DIRECTION: Record<PromptSort, PromptSortDirection> = {
  prompt: "asc",
  persona: "asc",
  ai: "asc",
  mention: "desc",
  rank: "asc",
  sov: "desc",
  lastRun: "asc",
  status: "asc",
};

const PROMPT_STATUS_ORDER: Record<PromptItem["status"], number> = {
  active: 0,
  disabled: 1,
  archived: 2,
};

type ProjectPromptRecord = {
  id: string;
  text: string;
  intent?: string;
  modelIds?: string[];
  schedule?: PromptSchedule;
  status?: PromptItem["status"];
  isActive: boolean;
  createdAt?: string;
  updatedAt?: string;
};

type PromptPageResult = {
  items: ProjectPromptRecord[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNext: boolean;
  hasPrevious: boolean;
};

type PromptEditorMode = "create" | "edit";

type SavePromptEditorInput = {
  mode: PromptEditorMode;
  promptId?: string;
  text: string;
  modelIds: AIModel[];
  schedule: PromptSchedule;
  status: PromptItem["status"];
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function getField<T = unknown>(obj: Record<string, unknown>, keys: string[]): T | undefined {
  for (const key of keys) {
    if (key in obj) return obj[key] as T;
  }
  return undefined;
}

function unwrapSuccessEnvelope(value: unknown): unknown {
  if (!isRecord(value)) return value;
  if (value.success === true && "data" in value) {
    return value.data;
  }
  return value;
}

function getString(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function getBool(value: unknown): boolean {
  return value === true;
}

function getNumber(value: unknown): number {
  return typeof value === "number" && Number.isFinite(value) ? value : 0;
}

function normalizePromptStatus(value: unknown): PromptItem["status"] | undefined {
  const raw = getString(value).toLowerCase();
  if (raw === "active" || raw === "disabled" || raw === "archived") {
    return raw;
  }
  return undefined;
}

function dedupeModels(models: string[]): string[] {
  const seen = new Set<string>();
  const unique: string[] = [];

  for (const model of models) {
    const value = model.trim();
    if (!value) continue;
    const key = normalizeModelName(value);
    if (seen.has(key)) continue;
    seen.add(key);
    unique.push(value);
  }

  return unique;
}

function getModelLookupKeys(values: Array<string | undefined | null>) {
  return values
    .map((value) => normalizeModelName(value || ""))
    .filter(Boolean);
}

function normalizePromptScheduleValue(input: unknown): PromptSchedule {
  if (!isRecord(input)) return defaultPromptSchedule();
  const mode = getString(getField(input, ["mode", "Mode"])) === "per_model" ? "per_model" : "global";
  const cron = getString(getField(input, ["cron", "Cron"])) || DEFAULT_PROMPT_CRON;
  const timezone = getString(getField(input, ["timezone", "Timezone"])) || DEFAULT_PROMPT_TIMEZONE;
  const rawOverrides = getField<Record<string, unknown>>(input, ["modelCrons", "ModelCrons"]);
  const modelCrons = Object.fromEntries(
    Object.entries(rawOverrides ?? {})
      .map(([modelId, cronValue]) => [modelId.trim(), getString(cronValue)])
      .filter(([modelId, cronValue]) => modelId !== "" && cronValue !== ""),
  );

  return {
    mode,
    cron,
    timezone,
    modelCrons,
  };
}

function buildScopedPromptMetrics(item: PromptItem, models: string[]): PromptItem {
  const scopedModels = dedupeModels(models);
  const normalizedScopedModels = new Set(
    scopedModels.map((model) => normalizeModelName(model)),
  );
  const scopedRuns =
    normalizedScopedModels.size === 0
      ? item.runs
      : item.runs.filter((run) =>
          normalizedScopedModels.has(normalizeModelName(run.model)),
        );

  const mentionRate =
    scopedRuns.length > 0
      ? Math.round(
          (scopedRuns.filter((run) => run.mention).length / scopedRuns.length) *
            100,
        )
      : 0;
  const rankedRuns = scopedRuns.filter((run) => typeof run.rank === "number");
  const rank =
    rankedRuns.length > 0
      ? Number(
          (
            rankedRuns.reduce((sum, run) => sum + (run.rank ?? 0), 0) /
            rankedRuns.length
          ).toFixed(1),
        )
      : 9.9;
  const sov =
    scopedRuns.length > 0
      ? Math.round(
          scopedRuns.reduce((sum, run) => sum + run.score, 0) /
            scopedRuns.length,
        )
      : 0;
  const lastRunMinutes =
    scopedRuns.length > 0
      ? Math.min(...scopedRuns.map((run) => run.minutesAgo))
      : 999999;
  const trendSeed = scopedRuns.slice(0, 7).map((run) => run.score);
  const trend30d =
    trendSeed.length > 0
      ? Array.from(
          { length: 7 },
          (_, trendIndex) =>
            trendSeed[trendIndex] ?? trendSeed[trendSeed.length - 1] ?? 0,
        )
      : [0, 0, 0, 0, 0, 0, 0];

  return {
    ...item,
    models: scopedModels,
    runs: scopedRuns,
    effectiveCron: item.effectiveCron,
    effectiveScheduleLabel: item.effectiveScheduleLabel,
    effectiveScheduleSource: item.effectiveScheduleSource,
    mentionRate,
    rank,
    sov,
    lastRunMinutes,
    trend30d,
  };
}

function getPromptSelectionKey(item: PromptItem, rowMode: PromptRowMode) {
  return rowMode === "model" ? item.id : item.sourcePromptId || item.id;
}

function readSelectedOrganizationId(): string {
  if (typeof window === "undefined") return "";
  try {
    return window.localStorage.getItem(SELECTED_ORG_KEY)?.trim() ?? "";
  } catch {
    return "";
  }
}

function normalizePromptPage(value: unknown): PromptPageResult {
  const payload = unwrapSuccessEnvelope(value);
  const record = isRecord(payload) ? payload : {};
  const rawItems = Array.isArray(payload)
    ? payload
    : Array.isArray(record.items)
      ? record.items
      : [];
  const items = rawItems
    .filter((entry): entry is Record<string, unknown> => isRecord(entry))
    .map(normalizeProjectPromptRecord)
    .filter((item) => item.id !== "" && item.text !== "");
  const isLegacyArray = Array.isArray(payload);
  const total = isLegacyArray ? items.length : getNumber(getField(record, ["total", "Total"]));
  const page = isLegacyArray ? 1 : Math.max(1, getNumber(getField(record, ["page", "Page"])) || 1);
  const pageSize = isLegacyArray
    ? Math.max(items.length, PROMPTS_PAGE_SIZE)
    : Math.max(1, getNumber(getField(record, ["pageSize", "PageSize"])) || PROMPTS_PAGE_SIZE);
  const totalPages = isLegacyArray
    ? (items.length > 0 ? 1 : 0)
    : Math.max(0, getNumber(getField(record, ["totalPages", "TotalPages"])));
  const hasNext = isLegacyArray ? false : getBool(getField(record, ["hasNext", "HasNext"]));
  const hasPrevious = isLegacyArray ? false : getBool(getField(record, ["hasPrevious", "HasPrevious"]));

  return {
    items,
    total,
    page,
    pageSize,
    totalPages,
    hasNext,
    hasPrevious,
  };
}

function normalizeProjectPromptRecord(entry: Record<string, unknown>): ProjectPromptRecord {
  return {
    id: getString(getField(entry, ["id", "ID"])),
    text: getString(getField(entry, ["text", "Text"])),
    intent: getString(getField(entry, ["intent", "Intent"])) || undefined,
    modelIds: dedupeModels(
      (getField(entry, ["modelIds", "ModelIds"]) as unknown[] | undefined)?.filter(
        (item): item is string => typeof item === "string",
      ) ?? [],
    ),
    schedule: normalizePromptScheduleValue(getField(entry, ["schedule", "Schedule"])),
    status: normalizePromptStatus(getField(entry, ["status", "Status"])),
    isActive: getBool(getField(entry, ["isActive", "IsActive"])),
    createdAt: getString(getField(entry, ["createdAt", "CreatedAt"])) || undefined,
    updatedAt: getString(getField(entry, ["updatedAt", "UpdatedAt"])) || undefined,
  };
}

function formatModelProvider(value: string): string {
  const normalized = value.trim();
  if (!normalized) return "AI provider";
  return normalized
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

async function loadPromptPage(
  apiBaseURL: string,
  organizationId: string,
  projectId: string,
  page: number,
  pageSize: number,
  search: string,
  signal?: AbortSignal,
): Promise<PromptPageResult> {
  const response = await gatewayJSON<unknown>(
    apiBaseURL,
    apiRoutes.projects.prompts(projectId, { page, pageSize, search }),
    {
      method: "GET",
      organizationId,
      signal,
    },
  );

  if (!response.ok) {
    throw new Error("Impossible de charger les prompts.");
  }

  return normalizePromptPage(response.data);
}

async function loadAllPromptPages(
  apiBaseURL: string,
  organizationId: string,
  projectId: string,
  search: string,
  signal?: AbortSignal,
): Promise<ProjectPromptRecord[]> {
  const firstPage = await loadPromptPage(
    apiBaseURL,
    organizationId,
    projectId,
    1,
    PROMPTS_CATALOG_PAGE_SIZE,
    search,
    signal,
  );

  if (firstPage.totalPages <= 1) {
    return firstPage.items;
  }

  const remainingPages = await Promise.all(
    Array.from({ length: firstPage.totalPages - 1 }, (_, index) =>
      loadPromptPage(
        apiBaseURL,
        organizationId,
        projectId,
        index + 2,
        PROMPTS_CATALOG_PAGE_SIZE,
        search,
        signal,
      ),
    ),
  );

  return [firstPage, ...remainingPages].flatMap((page) => page.items);
}

async function patchPromptModels(
  apiBaseURL: string,
  organizationId: string,
  promptId: string,
  modelIds: string[],
): Promise<void> {
  const response = await gatewayJSON<unknown>(
    apiBaseURL,
    apiRoutes.prompts.update(promptId),
    {
      method: "PATCH",
      organizationId,
      body: JSON.stringify({ modelIds }),
    },
  );

  if (!response.ok) {
    throw new Error("Impossible de mettre a jour la couverture IA du prompt.");
  }
}

async function patchPromptSchedule(
  apiBaseURL: string,
  organizationId: string,
  promptId: string,
  schedule: PromptSchedule,
): Promise<void> {
  const response = await gatewayJSON<unknown>(
    apiBaseURL,
    apiRoutes.prompts.update(promptId),
    {
      method: "PATCH",
      organizationId,
      body: JSON.stringify({ schedule }),
    },
  );

  if (!response.ok) {
    throw new Error("Impossible de mettre a jour la cadence d'analyse du prompt.");
  }
}

async function createProjectPrompt(
  apiBaseURL: string,
  organizationId: string,
  projectId: string,
  text: string,
): Promise<ProjectPromptRecord> {
  const response = await gatewayJSON<unknown>(
    apiBaseURL,
    apiRoutes.projects.prompts(projectId),
    {
      method: "POST",
      organizationId,
      body: JSON.stringify({ prompts: [text] }),
    },
  );

  if (!response.ok) {
    throw new Error("Impossible de creer le prompt.");
  }

  const payload = unwrapSuccessEnvelope(response.data);
  const rawItems = Array.isArray(payload)
    ? payload
    : isRecord(payload) && Array.isArray(payload.prompts)
      ? payload.prompts
      : isRecord(payload) && Array.isArray(payload.items)
        ? payload.items
        : [];
  const firstItem = rawItems.find((entry): entry is Record<string, unknown> => isRecord(entry));

  if (!firstItem) {
    throw new Error("Le backend n'a pas retourne le prompt cree.");
  }

  return normalizeProjectPromptRecord(firstItem);
}

async function patchPrompt(
  apiBaseURL: string,
  organizationId: string,
  promptId: string,
  input: {
    text?: string;
    modelIds?: string[];
    schedule?: PromptSchedule;
    status?: PromptItem["status"];
  },
): Promise<void> {
  const response = await gatewayJSON<unknown>(
    apiBaseURL,
    apiRoutes.prompts.update(promptId),
    {
      method: "PATCH",
      organizationId,
      body: JSON.stringify(input),
    },
  );

  if (!response.ok) {
    throw new Error("Impossible d'enregistrer le prompt.");
  }
}

async function deleteProjectPrompt(
  apiBaseURL: string,
  organizationId: string,
  promptId: string,
): Promise<void> {
  const response = await gatewayJSON<unknown>(
    apiBaseURL,
    apiRoutes.prompts.update(promptId),
    {
      method: "DELETE",
      organizationId,
    },
  );

  if (!response.ok) {
    throw new Error("Impossible de supprimer le prompt.");
  }
}

function compareStrings(a: string, b: string): number {
  return a.localeCompare(b, "fr", { sensitivity: "base", numeric: true });
}

function comparePromptItems(a: PromptItem, b: PromptItem, field: PromptSort): number {
  if (field === "prompt") return compareStrings(a.prompt, b.prompt);

  if (field === "persona") {
    return compareStrings(a.persona?.trim() || "\uffff", b.persona?.trim() || "\uffff");
  }

  if (field === "ai") {
    const aModels = a.models.map((model) => normalizeModelName(model)).join("|");
    const bModels = b.models.map((model) => normalizeModelName(model)).join("|");
    return compareStrings(aModels || "\uffff", bModels || "\uffff");
  }

  if (field === "mention") return a.mentionRate - b.mentionRate;
  if (field === "rank") return a.rank - b.rank;
  if (field === "sov") return a.sov - b.sov;
  if (field === "lastRun") return a.lastRunMinutes - b.lastRunMinutes;

  if (field === "status") {
    return PROMPT_STATUS_ORDER[a.status] - PROMPT_STATUS_ORDER[b.status];
  }

  return compareStrings(a.prompt, b.prompt);
}

function sortPromptItems(
  rows: PromptItem[],
  field: PromptSort,
  direction: PromptSortDirection,
): PromptItem[] {
  const multiplier = direction === "asc" ? 1 : -1;

  return [...rows].sort((a, b) => {
    const primary = comparePromptItems(a, b, field);
    if (primary !== 0) return primary * multiplier;
    return compareStrings(a.prompt, b.prompt);
  });
}

function buildModelScopedPromptRows(prompts: PromptItem[]): PromptItem[] {
  return prompts.flatMap((prompt) => {
    const sourcePromptId = prompt.sourcePromptId || prompt.id;
    const runsByModel = prompt.runs.reduce((map, run) => {
      const bucket = map.get(run.model) ?? [];
      bucket.push(run);
      map.set(run.model, bucket);
      return map;
    }, new Map<string, typeof prompt.runs>());

    const models =
      prompt.models.length > 0
        ? prompt.models
        : runsByModel.size > 0
          ? Array.from(runsByModel.keys())
          : [];

    return models.map((model, index) => {
      const runs = [...(runsByModel.get(model) ?? [])].sort((a, b) => a.minutesAgo - b.minutesAgo);
      const overrideCron = prompt.schedule.modelCrons[model];
      const mentionRate =
        runs.length > 0
          ? Math.round((runs.filter((item) => item.mention).length / runs.length) * 100)
          : 0;
      const rankedRuns = runs.filter((item) => typeof item.rank === "number");
      const rank =
        rankedRuns.length > 0
          ? Number(
              (
                rankedRuns.reduce((sum, item) => sum + (item.rank ?? 0), 0) / rankedRuns.length
              ).toFixed(1),
            )
          : 9.9;
      const sov =
        runs.length > 0
          ? Math.round(runs.reduce((sum, item) => sum + item.score, 0) / runs.length)
          : 0;
      const lastRunMinutes =
        runs.length > 0
          ? Math.min(...runs.map((item) => item.minutesAgo))
          : prompt.lastRunMinutes;
      const trendSeed = runs.slice(0, 7).map((item) => item.score);
      const trend30d =
        trendSeed.length > 0
          ? Array.from(
              { length: 7 },
              (_, trendIndex) => trendSeed[trendIndex] ?? trendSeed[trendSeed.length - 1] ?? 0,
            )
          : prompt.trend30d;

      return {
        ...prompt,
        id: `${sourcePromptId}::${normalizeModelName(model) || index}`,
        sourcePromptId,
        rowMode: "model" as PromptRowMode,
        models: model ? [model] : [],
        effectiveCron: overrideCron || prompt.schedule.cron,
        effectiveScheduleLabel: promptScheduleLabel(prompt.schedule, overrideCron),
        effectiveScheduleSource: overrideCron ? "override" : "global",
        mentionRate,
        rank,
        sov,
        lastRunMinutes,
        trend30d,
        runs,
      };
    });
  });
}

export function usePromptsResponsesState(apiBaseURL: string) {
  const queryClient = useQueryClient();
  const { data: monitoringData, mode, projectId } = useMonitoringData();
  const activeProjectId = projectId || monitoringData.project.id || "";
  const projectModels = monitoringData.models;
  const liveModels = useMemo(
    () => projectModels.filter((item) => item.live),
    [projectModels],
  );
  const modelMeta = useMemo(() => {
    const map = new Map<string, ModelVisual>();
    for (const model of projectModels) {
      const keys = [
        model.providerModelId,
        model.groupName,
        model.displayName,
        model.id,
      ]
        .map((value) => normalizeModelName(value))
        .filter(Boolean);
      const entry = {
        icon: toSafeImageAssetPath(model.iconPath),
        description: model.description || model.displayName || model.providerModelId,
        label: model.groupName || model.displayName || model.providerModelId || model.id,
        provider: formatModelProvider(model.provider),
        name: model.displayName || model.providerModelId || model.id,
      };
      for (const key of keys) {
        map.set(key, entry);
      }
    }
    return map;
  }, [projectModels]);

  const getModelVisual = (model: string): ModelVisual =>
    modelMeta.get(normalizeModelName(model)) || {
      icon: "/models/openai.svg",
      description: "Modele IA",
      label: model,
      provider: "OpenAI",
      name: model,
    };

  const responseAvailableModels = useMemo(
    () =>
      dedupeModels([
        ...liveModels.map((item) => item.providerModelId),
        ...monitoringData.recent_prompts.map(
          (item) =>
            item.modelProviderModelId ||
            item.modelDisplayName ||
            item.modelGroupName ||
            item.modelId,
        ),
      ]),
    [monitoringData.recent_prompts, liveModels],
  );
  const promptAvailableModels = useMemo(
    () => dedupeModels(liveModels.map((item) => item.providerModelId)),
    [liveModels],
  );
  const activeModelKeys = useMemo(
    () =>
      new Set(
        liveModels.flatMap((item) =>
          getModelLookupKeys([
            item.id,
            item.providerModelId,
            item.displayName,
            item.groupName,
          ]),
        ),
      ),
    [liveModels],
  );
  const availablePersonas = useMemo(
    () =>
      Array.from(
        new Set(
          monitoringData.recent_prompts
            .map((item) => item.persona?.trim() || "")
            .filter(Boolean),
        ),
      ),
    [monitoringData.recent_prompts],
  );
  const availableCompetitors = useMemo(
    () => monitoringData.project.competitors.map((item) => item.name),
    [monitoringData.project.competitors],
  );

  const [organizationId, setOrganizationId] = useState("");
  const [period, setPeriod] = useState<PeriodKey>("7d");
  const [dateRange, setDateRange] = useState<DateRange | undefined>(undefined);
  const [tab, setTab] = useState<"prompts" | "responses">("prompts");
  const [persona, setPersona] = useState<"all" | Persona>("all");
  const [search, setSearch] = useState("");
  const deferredSearch = useDeferredValue(search.trim());
  const [selectedPromptModels, setSelectedPromptModels] = useState<AIModel[]>([]);
  const [selectedResponseModels, setSelectedResponseModels] = useState<AIModel[]>([]);
  const [promptSort, setPromptSort] = useState<PromptSort>("mention");
  const [promptSortDirection, setPromptSortDirection] = useState<PromptSortDirection>("desc");
  const [viewMode, setViewMode] = useState<ResponseView>("table");
  const [onlyErrors, setOnlyErrors] = useState(false);
  const [criticalOnly, setCriticalOnly] = useState(false);
  const [noMentionOnly, setNoMentionOnly] = useState(false);
  const [showHistorical, setShowHistorical] = useState(true);
  const [topCompetitor, setTopCompetitor] = useState<"all" | string>("all");
  const [selectedPromptIds, setSelectedPromptIds] = useState<string[]>([]);
  const [selectedPromptId, setSelectedPromptId] = useState<string | null>(null);
  const [isPromptDetailsOpen, setIsPromptDetailsOpen] = useState(false);
  const [selectedResponseId, setSelectedResponseId] = useState<string | null>(null);
  const [focusPromptId, setFocusPromptId] = useState<string | null>(null);
  const [manualPrompts, setManualPrompts] = useState<PromptItem[]>([]);
  const [modelsPopoverOpen, setModelsPopoverOpen] = useState(false);
  const [promptPage, setPromptPage] = useState(1);
  const [promptRowMode, setPromptRowMode] = useState<PromptRowMode>("global");
  const [showArchived, setShowArchived] = useState(false);
  const [responseVisibleCount, setResponseVisibleCount] = useState(RESPONSES_BATCH_SIZE);
  const [hiddenPromptIds, setHiddenPromptIds] = useState<string[]>([]);
  const [promptEditorState, setPromptEditorState] = useState<{ mode: PromptEditorMode; promptId?: string } | null>(null);
  const [editingPromptModelsId, setEditingPromptModelsId] = useState<string | null>(null);
  const [editingPromptScheduleId, setEditingPromptScheduleId] = useState<string | null>(null);

  useEffect(() => {
    setOrganizationId(readSelectedOrganizationId());
  }, []);

  const promptsCatalogQuery = useQuery<ProjectPromptRecord[]>({
    queryKey: appQueryKeys.promptsCatalog(
      apiBaseURL,
      organizationId,
      activeProjectId,
      deferredSearch,
      promptSort,
      promptSortDirection,
    ),
    enabled: apiBaseURL.trim() !== "" && organizationId !== "" && activeProjectId !== "",
    placeholderData: (previous) => previous,
    queryFn: ({ signal }) =>
      loadAllPromptPages(
        apiBaseURL,
        organizationId,
        activeProjectId,
        deferredSearch,
        signal,
      ),
  });

  useEffect(() => {
    setPromptPage(1);
  }, [
    deferredSearch,
    period,
    dateRange?.from?.toISOString(),
    dateRange?.to?.toISOString(),
    persona,
    selectedPromptModels.join("|"),
    promptRowMode,
    showArchived,
    promptSort,
    promptSortDirection,
  ]);

  useEffect(() => {
    setSelectedPromptIds([]);
  }, [promptRowMode]);

  useEffect(() => {
    if (promptAvailableModels.length === 0) return;
    setSelectedPromptModels((current) => {
      const kept = current.filter((model) => promptAvailableModels.includes(model));
      if (kept.length > 0) return kept;
      return promptAvailableModels;
    });
  }, [promptAvailableModels]);

  useEffect(() => {
    if (responseAvailableModels.length === 0) return;
    setSelectedResponseModels((current) => {
      const kept = current.filter((model) => responseAvailableModels.includes(model));
      if (kept.length > 0) return kept;
      return responseAvailableModels;
    });
  }, [responseAvailableModels]);

  const serverPromptItems = useMemo(
    () =>
      buildPromptPageItems({
        projectPrompts: promptsCatalogQuery.data ?? [],
        recentPrompts: monitoringData.recent_prompts.filter((item) =>
          activeModelKeys.has(normalizeModelName(item.modelId || item.modelProviderModelId)),
        ),
        competitors: monitoringData.project.competitors,
        availableModels: promptAvailableModels,
        stages: STAGES,
      }),
    [
      promptsCatalogQuery.data,
      monitoringData.recent_prompts,
      monitoringData.project.competitors,
      activeModelKeys,
      promptAvailableModels,
    ],
  );

  const bulkPromptStatusMutation = useMutation({
    mutationFn: async ({
      promptIds,
      status,
    }: {
      promptIds: string[];
      status: PromptItem["status"];
    }) => {
      const response = await gatewayJSON<unknown>(
        apiBaseURL,
        apiRoutes.projects.promptsStatus(activeProjectId),
        {
          method: "PATCH",
          organizationId,
          body: JSON.stringify({ promptIds, status }),
        },
      );

      if (!response.ok) {
        throw new Error("Impossible de mettre a jour le statut des prompts.");
      }

      return { promptIds, status };
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({
        queryKey: appQueryKeys.promptsCatalog(
          apiBaseURL,
          organizationId,
          activeProjectId,
          deferredSearch,
          promptSort,
          promptSortDirection,
        ),
      });
    },
  });

  const updatePromptModelsMutation = useMutation({
    mutationFn: async ({
      promptId,
      modelIds,
    }: {
      promptId: string;
      modelIds: AIModel[];
    }) => {
      await patchPromptModels(apiBaseURL, organizationId, promptId, modelIds);
      return { promptId, modelIds };
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({
        queryKey: appQueryKeys.promptsCatalog(
          apiBaseURL,
          organizationId,
          activeProjectId,
          deferredSearch,
          promptSort,
          promptSortDirection,
        ),
      });
      setEditingPromptModelsId(null);
    },
  });

  const updatePromptScheduleMutation = useMutation({
    mutationFn: async ({
      promptId,
      schedule,
    }: {
      promptId: string;
      schedule: PromptSchedule;
    }) => {
      await patchPromptSchedule(apiBaseURL, organizationId, promptId, schedule);
      return { promptId, schedule };
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({
        queryKey: appQueryKeys.promptsCatalog(
          apiBaseURL,
          organizationId,
          activeProjectId,
          deferredSearch,
          promptSort,
          promptSortDirection,
        ),
      });
      setEditingPromptScheduleId(null);
    },
  });

  const savePromptEditorMutation = useMutation({
    mutationFn: async ({
      mode: nextMode,
      promptId,
      text,
      modelIds,
      schedule,
      status,
    }: SavePromptEditorInput) => {
      const trimmedText = text.trim();
      if (!trimmedText) {
        throw new Error("Le prompt ne peut pas etre vide.");
      }

      const resolvedModels = dedupeModels(modelIds).filter((model) =>
        promptAvailableModels.includes(model),
      );
      const nextModels =
        resolvedModels.length > 0
          ? resolvedModels
          : promptAvailableModels.slice(0, 1);
      const nextSchedule = normalizePromptScheduleValue(schedule);
      const manualPromptIds = new Set(manualPrompts.map((item) => item.sourcePromptId || item.id));

      if (nextMode === "create") {
        if (mode === "demo" || !organizationId || !activeProjectId) {
          const nextId = `p${Date.now()}`;
          const newPrompt: PromptItem = {
            id: nextId,
            sourcePromptId: nextId,
            rowMode: "global",
            prompt: trimmedText,
            stage: "Awareness",
            models: nextModels,
            schedule: nextSchedule,
            effectiveCron: nextSchedule.cron,
            effectiveScheduleLabel: promptScheduleLabel(nextSchedule),
            effectiveScheduleSource: "global",
            mentionRate: 0,
            rank: 9.9,
            sov: 0,
            lastRunMinutes: 1,
            trend30d: [0, 0, 0, 0, 0, 0, 0],
            status,
            runs: [],
          };
          setManualPrompts((prev) => [newPrompt, ...prev]);
          return;
        }

        const createdPrompt = await createProjectPrompt(apiBaseURL, organizationId, activeProjectId, trimmedText);
        await patchPrompt(apiBaseURL, organizationId, createdPrompt.id, {
          modelIds: nextModels,
          schedule: nextSchedule,
          status,
        });
        return;
      }

      if (!promptId) {
        throw new Error("Prompt introuvable.");
      }

      if (manualPromptIds.has(promptId)) {
        setManualPrompts((prev) =>
          prev.map((item) =>
            (item.sourcePromptId || item.id) === promptId
              ? {
                  ...item,
                  prompt: trimmedText,
                  models: nextModels,
                  schedule: nextSchedule,
                  effectiveCron: nextSchedule.cron,
                  effectiveScheduleLabel: promptScheduleLabel(nextSchedule),
                  effectiveScheduleSource: "global",
                  status,
                }
              : item,
          ),
        );
        return;
      }

      if (!organizationId || !activeProjectId) {
        throw new Error("Impossible d'enregistrer le prompt.");
      }

      await patchPrompt(apiBaseURL, organizationId, promptId, {
        text: trimmedText,
        modelIds: nextModels,
        schedule: nextSchedule,
        status,
      });
    },
    onSuccess: async () => {
      setPromptPage(1);
      setPromptEditorState(null);
      if (!organizationId || !activeProjectId) return;
      await queryClient.invalidateQueries({
        queryKey: appQueryKeys.promptsCatalog(
          apiBaseURL,
          organizationId,
          activeProjectId,
          deferredSearch,
          promptSort,
          promptSortDirection,
        ),
      });
    },
  });

  const deletePromptMutation = useMutation({
    mutationFn: async (promptId: string) => {
      await deleteProjectPrompt(apiBaseURL, organizationId, promptId);
      return promptId;
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({
        queryKey: appQueryKeys.promptsCatalog(
          apiBaseURL,
          organizationId,
          activeProjectId,
          deferredSearch,
          promptSort,
          promptSortDirection,
        ),
      });
    },
    onError: (_error, promptId) => {
      setHiddenPromptIds((prev) => prev.filter((item) => item !== promptId));
    },
  });

  const basePrompts = useMemo(() => {
    const searchLower = deferredSearch.toLowerCase();
    const visibleManualPrompts = manualPrompts.filter((item) =>
      searchLower === "" ? true : item.prompt.toLowerCase().includes(searchLower),
    );
    const merged = [...visibleManualPrompts, ...serverPromptItems];
    return merged
      .filter((item) => !hiddenPromptIds.includes(item.sourcePromptId || item.id))
      .map((item) => buildScopedPromptMetrics(item, item.models));
  }, [deferredSearch, hiddenPromptIds, manualPrompts, serverPromptItems]);

  const prompts = useMemo(
    () => (promptRowMode === "global" ? basePrompts : buildModelScopedPromptRows(basePrompts)),
    [basePrompts, promptRowMode],
  );

  const allResponses = useMemo(
    () =>
      buildResponseRows({
        recentPrompts: monitoringData.recent_prompts,
        competitors: monitoringData.project.competitors,
        availableModels: responseAvailableModels,
        stages: STAGES,
      }).map((item) => ({
        ...item,
        isHistorical: !activeModelKeys.has(normalizeModelName(item.model)),
      })),
    [
      activeModelKeys,
      monitoringData.project.competitors,
      monitoringData.recent_prompts,
      responseAvailableModels,
    ],
  );

  const rangeMinutes = useMemo(() => {
    if (period !== "custom") return PERIOD_TO_MINUTES[period];
    if (!dateRange?.from) return PERIOD_TO_MINUTES["90d"];
    const to = dateRange.to ?? dateRange.from;
    const days = Math.max(1, differenceInCalendarDays(to, dateRange.from) + 1);
    return days * 24 * 60;
  }, [dateRange, period]);

  const filteredPromptRows = useMemo(() => {
    const searchLower = deferredSearch.toLowerCase();
    const rows = prompts.filter((item) => {
      const matchesPeriod = item.lastRunMinutes <= rangeMinutes || item.runs.length === 0;
      const matchesModel =
        selectedPromptModels.length === 0 ||
        item.models.length === 0 ||
        item.models.some((model) => selectedPromptModels.includes(model));
      const matchesPersona = persona === "all" || item.persona === persona;
      const matchesSearch = searchLower === "" || item.prompt.toLowerCase().includes(searchLower);
      const matchesArchive = showArchived || item.status !== "archived";
      return matchesPeriod && matchesModel && matchesPersona && matchesSearch && matchesArchive;
    });

    return sortPromptItems(rows, promptSort, promptSortDirection);
  }, [
    deferredSearch,
    persona,
    promptSort,
    promptSortDirection,
    prompts,
    rangeMinutes,
    selectedPromptModels,
    showArchived,
  ]);

  const promptTotalItems = filteredPromptRows.length;
  const promptTotalPages = Math.max(1, Math.ceil(promptTotalItems / PROMPTS_PAGE_SIZE));

  useEffect(() => {
    if (promptPage > promptTotalPages) {
      setPromptPage(promptTotalPages);
    }
  }, [promptPage, promptTotalPages]);

  const filteredPrompts = useMemo(() => {
    const start = (promptPage - 1) * PROMPTS_PAGE_SIZE;
    return filteredPromptRows.slice(start, start + PROMPTS_PAGE_SIZE);
  }, [filteredPromptRows, promptPage]);

  const filteredResponses = useMemo(() => {
    const searchLower = search.toLowerCase().trim();
    return allResponses
      .filter((item) => {
        const matchesPeriod = item.minutesAgo <= rangeMinutes;
        const matchesModel =
          selectedResponseModels.length === 0 ||
          selectedResponseModels.includes(item.model);
        const matchesPersona = persona === "all" || item.persona === persona;
        const matchesSearch = searchLower.length === 0 || item.prompt.toLowerCase().includes(searchLower);
        const matchesError = !onlyErrors || Boolean(item.error);
        const matchesCritical = !criticalOnly || item.critical;
        const matchesNoMention = !noMentionOnly || !item.mention;
        const matchesHistory = showHistorical || !item.isHistorical;
        const matchesCompetitor =
          topCompetitor === "all" ||
          item.competitors.includes(topCompetitor) ||
          item.competitor === topCompetitor;
        const matchesFocusedPrompt = !focusPromptId || item.promptId === focusPromptId;
        return (
          matchesPeriod &&
          matchesModel &&
          matchesPersona &&
          matchesSearch &&
          matchesError &&
          matchesCritical &&
          matchesNoMention &&
          matchesHistory &&
          matchesCompetitor &&
          matchesFocusedPrompt
        );
      })
      .sort((a, b) => a.minutesAgo - b.minutesAgo);
  }, [
    allResponses,
    criticalOnly,
    focusPromptId,
    noMentionOnly,
    onlyErrors,
    rangeMinutes,
    persona,
    search,
    selectedResponseModels,
    showHistorical,
    topCompetitor,
  ]);

  useEffect(() => {
    const selectablePromptIds = new Set(
      filteredPromptRows.map((item) =>
        getPromptSelectionKey(item, promptRowMode),
      ),
    );
    setSelectedPromptIds((current) => current.filter((id) => selectablePromptIds.has(id)));
    setSelectedPromptId((current) =>
      current && filteredPromptRows.some((item) => item.id === current) ? current : filteredPromptRows[0]?.id ?? null,
    );
  }, [filteredPromptRows, promptRowMode]);

  useEffect(() => {
    setResponseVisibleCount(RESPONSES_BATCH_SIZE);
  }, [
    criticalOnly,
    dateRange?.from?.toISOString(),
    dateRange?.to?.toISOString(),
    focusPromptId,
    noMentionOnly,
    onlyErrors,
    period,
    persona,
    search,
    selectedResponseModels.join("|"),
    showHistorical,
    topCompetitor,
  ]);

  useEffect(() => {
    setResponseVisibleCount((current) => Math.min(Math.max(RESPONSES_BATCH_SIZE, current), filteredResponses.length || RESPONSES_BATCH_SIZE));
  }, [filteredResponses.length]);

  const visibleResponses = useMemo(
    () => filteredResponses.slice(0, responseVisibleCount),
    [filteredResponses, responseVisibleCount],
  );

  const selectedPrompt = filteredPromptRows.find((item) => item.id === selectedPromptId) ?? null;
  const selectedResponse = allResponses.find((item) => item.id === selectedResponseId) ?? null;
  const toolbarAvailableModels =
    tab === "responses" ? responseAvailableModels : promptAvailableModels;
  const toolbarSelectedModels =
    tab === "responses" ? selectedResponseModels : selectedPromptModels;
  const allModelsSelected =
    toolbarAvailableModels.length > 0 &&
    toolbarSelectedModels.length === toolbarAvailableModels.length &&
    toolbarAvailableModels.every((model) => toolbarSelectedModels.includes(model));

  const hasActiveGlobalFilters =
    period !== "7d" ||
    persona !== "all" ||
    showArchived ||
    search.trim().length > 0 ||
    toolbarSelectedModels.length !== toolbarAvailableModels.length ||
    toolbarAvailableModels.some((model) => !toolbarSelectedModels.includes(model)) ||
    (tab === "responses" && !showHistorical);

  const clearFilters = () => {
    setPeriod("7d");
    setDateRange(undefined);
    setSelectedPromptModels(promptAvailableModels);
    setSelectedResponseModels(responseAvailableModels);
    setPersona("all");
    setShowArchived(false);
    setSearch("");
    setOnlyErrors(false);
    setCriticalOnly(false);
    setNoMentionOnly(false);
    setShowHistorical(true);
    setTopCompetitor("all");
    setFocusPromptId(null);
    setPromptPage(1);
  };

  const toggleModel = (model: AIModel) => {
    if (allModelsSelected) {
      if (tab === "responses") {
        setSelectedResponseModels([model]);
      } else {
        setSelectedPromptModels([model]);
      }
      return;
    }
    if (tab === "responses") {
      setSelectedResponseModels((prev) =>
        prev.includes(model)
          ? prev.filter((item) => item !== model)
          : [...prev, model],
      );
      return;
    }
    setSelectedPromptModels((prev) =>
      prev.includes(model)
        ? prev.filter((item) => item !== model)
        : [...prev, model],
    );
  };

  const togglePromptSelection = (id: string) => {
    setSelectedPromptIds((prev) => (prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]));
  };

  const toggleSelectAllPrompts = (checked: boolean) => {
    if (!checked) {
      setSelectedPromptIds([]);
      return;
    }
    setSelectedPromptIds(
      Array.from(
        new Set(
          filteredPrompts.map((item) =>
            getPromptSelectionKey(item, promptRowMode),
          ),
        ),
      ),
    );
  };

  const changePromptSort = (nextSort: PromptSort) => {
    if (promptSort === nextSort) {
      setPromptSortDirection((current) => (current === "asc" ? "desc" : "asc"));
      return;
    }

    setPromptSort(nextSort);
    setPromptSortDirection(PROMPT_SORT_DEFAULT_DIRECTION[nextSort]);
  };

  const applyBulkStatus = (status: PromptItem["status"]) => {
    if (promptRowMode === "model") return;
    if (selectedPromptIds.length === 0) return;
    const targetPromptIds = Array.from(
      new Set(
        filteredPromptRows
          .filter((item) =>
            selectedPromptIds.includes(getPromptSelectionKey(item, promptRowMode)),
          )
          .map((item) => item.sourcePromptId || item.id),
      ),
    );
    if (targetPromptIds.length === 0) return;
    const manualPromptIds = new Set(manualPrompts.map((item) => item.sourcePromptId || item.id));
    const localPromptIds = targetPromptIds.filter((id) => manualPromptIds.has(id));
    const serverPromptIds = targetPromptIds.filter((id) => !manualPromptIds.has(id));

    if (localPromptIds.length > 0) {
      setManualPrompts((prev) =>
        prev.map((item) =>
          localPromptIds.includes(item.sourcePromptId || item.id)
            ? { ...item, status }
            : item,
        ),
      );
    }

    if (serverPromptIds.length > 0 && organizationId && activeProjectId) {
      bulkPromptStatusMutation.mutate({ promptIds: serverPromptIds, status });
    }
  };

  const openCreatePromptEditor = () => {
    setPromptEditorState({ mode: "create" });
  };

  const openEditPromptEditor = (promptId: string) => {
    setPromptEditorState({ mode: "edit", promptId });
  };

  const closePromptEditor = () => {
    if (savePromptEditorMutation.isPending) return;
    setPromptEditorState(null);
  };

  const savePromptEditor = (input: SavePromptEditorInput) => {
    savePromptEditorMutation.mutate(input);
  };

  const addAutoGeneratedPrompts = () => {
    setManualPrompts((prev) => [
      ...buildAutoGeneratedPrompts(promptAvailableModels, availablePersonas, STAGES),
      ...prev,
    ]);
    setPromptPage(1);
  };

  const addImportedPrompts = () => {
    const imported = buildImportedPrompts();
    setManualPrompts((prev) => [...imported, ...prev]);
    setPromptPage(1);
  };

  const deletePrompt = (id: string) => {
    let removedManual = false;
    setManualPrompts((prev) => {
      const next = prev.filter((item) => (item.sourcePromptId || item.id) !== id);
      removedManual = next.length !== prev.length;
      return next;
    });
    setSelectedPromptIds((prev) => prev.filter((item) => item !== id));
    if (selectedPromptId === id) setSelectedPromptId(null);

    if (removedManual) {
      return;
    }

    if (!organizationId || !activeProjectId) {
      setHiddenPromptIds((prev) => (prev.includes(id) ? prev : [...prev, id]));
      return;
    }

    setHiddenPromptIds((prev) => (prev.includes(id) ? prev : [...prev, id]));
    deletePromptMutation.mutate(id);
  };

  const updatePromptModels = (promptId: string, modelIds: AIModel[]) => {
    const nextModels = dedupeModels(modelIds).filter((model) =>
      promptAvailableModels.includes(model),
    );
    const resolvedModels =
      nextModels.length > 0 ? nextModels : promptAvailableModels.slice(0, 1);
    const manualPromptIds = new Set(
      manualPrompts.map((item) => item.sourcePromptId || item.id),
    );

    if (manualPromptIds.has(promptId)) {
      setManualPrompts((prev) =>
        prev.map((item) =>
          (item.sourcePromptId || item.id) === promptId
            ? { ...item, models: resolvedModels }
            : item,
        ),
      );
      setEditingPromptModelsId(null);
      return;
    }

    if (!organizationId || !activeProjectId) return;
    updatePromptModelsMutation.mutate({ promptId, modelIds: resolvedModels });
  };

  const updatePromptSchedule = (promptId: string, schedule: PromptSchedule) => {
    const manualPromptIds = new Set(
      manualPrompts.map((item) => item.sourcePromptId || item.id),
    );

    if (manualPromptIds.has(promptId)) {
      setManualPrompts((prev) =>
        prev.map((item) =>
          (item.sourcePromptId || item.id) === promptId
            ? {
                ...item,
                schedule,
                effectiveCron: schedule.cron,
                effectiveScheduleLabel: promptScheduleLabel(schedule),
                effectiveScheduleSource: "global",
              }
            : item,
        ),
      );
      setEditingPromptScheduleId(null);
      return;
    }

    if (!organizationId || !activeProjectId) return;
    updatePromptScheduleMutation.mutate({ promptId, schedule });
  };

  const loadMoreResponses = () => {
    setResponseVisibleCount((current) => Math.min(current + RESPONSES_BATCH_SIZE, filteredResponses.length));
  };

  const promptsLoading =
    promptsCatalogQuery.isLoading ||
    (promptsCatalogQuery.isFetching && !promptsCatalogQuery.data) ||
    bulkPromptStatusMutation.isPending ||
    savePromptEditorMutation.isPending ||
    deletePromptMutation.isPending ||
    updatePromptModelsMutation.isPending ||
    updatePromptScheduleMutation.isPending;

  return {
    mode,
    tab,
    setTab,
    prompts,
    filteredPrompts,
    filteredResponses: visibleResponses,
    filteredResponsesTotal: filteredResponses.length,
    hasMoreResponses: visibleResponses.length < filteredResponses.length,
    loadMoreResponses,
    selectedPrompt,
    selectedResponse,
    selectedPromptIds,
    setSelectedPromptId,
    setSelectedResponseId,
    isPromptDetailsOpen,
    setIsPromptDetailsOpen,
    period,
    setPeriod,
    dateRange,
    setDateRange,
    persona,
    setPersona,
    availablePersonas,
    search,
    setSearch,
    selectedModels: toolbarSelectedModels,
    availableModels: toolbarAvailableModels,
    editorAvailableModels: promptAvailableModels,
    allModelsSelected,
    modelsPopoverOpen,
    setModelsPopoverOpen,
    showArchived,
    setShowArchived,
    hasActiveGlobalFilters,
    clearFilters,
    toggleModel,
    promptSort,
    promptSortDirection,
    changePromptSort,
    promptRowMode,
    setPromptRowMode,
    getPromptSelectionKey: (item: PromptItem) =>
      getPromptSelectionKey(item, promptRowMode),
    toggleSelectAllPrompts,
    togglePromptSelection,
    applyBulkStatus,
    setFocusPromptId,
    deletePrompt,
    viewMode,
    setViewMode,
    onlyErrors,
    setOnlyErrors,
    criticalOnly,
    setCriticalOnly,
    noMentionOnly,
    setNoMentionOnly,
    showHistorical,
    setShowHistorical,
    topCompetitor,
    setTopCompetitor,
    availableCompetitors,
    promptEditorState,
    openCreatePromptEditor,
    openEditPromptEditor,
    closePromptEditor,
    savePromptEditor,
    savingPromptEditor: savePromptEditorMutation.isPending,
    editingPromptModelsId,
    setEditingPromptModelsId,
    updatePromptModels,
    updatingPromptModels: updatePromptModelsMutation.isPending,
    editingPromptScheduleId,
    setEditingPromptScheduleId,
    updatePromptSchedule,
    updatingPromptSchedule: updatePromptScheduleMutation.isPending,
    addAutoGeneratedPrompts,
    addImportedPrompts,
    getModelVisual,
    promptPage,
    setPromptPage,
    promptTotalItems,
    promptTotalPages,
    canPreviousPromptPage: promptPage > 1,
    canNextPromptPage: promptPage < promptTotalPages,
    promptsLoading,
  };
}
