// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type PermissionRolePolicy struct {
	ID             int64
	OrganizationID int64
	Role           string
	Action         string
	Resource       string
}
