// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package sqlc

import (
	"context"
)

const countMatchingPolicies = `-- name: CountMatchingPolicies :one
SELECT COUNT(1)
FROM permission_role_policies
WHERE organization_id = ANY($1::bigint[])
  AND role = ANY($2::text[])
  AND action = ANY($3::text[])
  AND resource = ANY($4::text[])
`

type CountMatchingPoliciesParams struct {
	Column1 []int64
	Column2 []string
	Column3 []string
	Column4 []string
}

func (q *Queries) CountMatchingPolicies(ctx context.Context, arg CountMatchingPoliciesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchingPolicies,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}
