// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountMatchingPolicies(ctx context.Context, arg CountMatchingPoliciesParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
