// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MemberRole struct {
	OrganizationID int64
	UserID         int64
	Role           string
}

type OrganizationInvitation struct {
	ID               int64
	OrganizationID   int64
	Email            string
	Role             string
	Token            string
	Message          string
	Status           string
	InvitedByUserID  int64
	AcceptedByUserID int64
	CreatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	RespondedAt      pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type Organization struct {
	ID          int64
	Name        string
	OwnerUserID int64
	CreatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type OrganizationMember struct {
	OrganizationID int64
	UserID         int64
	TeamID         pgtype.Int8
	AddedAt        pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Team struct {
	ID             int64
	OrganizationID int64
	Name           string
	CreatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}
