// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, owner_user_id, created_at, deleted_at)
VALUES ($1, $2, $3, NULL)
RETURNING id, name, owner_user_id, created_at, deleted_at
`

type CreateOrganizationParams struct {
	Name        string
	OwnerUserID int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.OwnerUserID, arg.CreatedAt)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO organization_invitations (
  organization_id,
  project_id,
  email,
  role,
  token,
  message,
  status,
  invited_by_user_id,
  accepted_by_user_id,
  created_at,
  expires_at,
  responded_at,
  deleted_at
)
SELECT o.id, $2, $3, $4, $5, $6, 'pending', $7, 0, $8, $9, NULL, NULL
FROM organizations o
WHERE o.id = $1
  AND o.deleted_at IS NULL
RETURNING id, organization_id, project_id, email, role, token, message, status, invited_by_user_id, accepted_by_user_id, created_at, expires_at, responded_at, deleted_at
`

type CreateInvitationParams struct {
	OrganizationID  int64
	ProjectID       string
	Email           string
	Role            string
	Token           string
	Message         string
	InvitedByUserID int64
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.Message,
		arg.InvitedByUserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Message,
		&i.Status,
		&i.InvitedByUserID,
		&i.AcceptedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RespondedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (organization_id, name, created_at, deleted_at)
SELECT o.id, $2, $3, NULL
FROM organizations o
WHERE o.id = $1
  AND o.deleted_at IS NULL
RETURNING id, organization_id, name, created_at, deleted_at
`

type CreateTeamParams struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.ID, arg.Name, arg.CreatedAt)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMemberByOrgAndUser = `-- name: GetMemberByOrgAndUser :one
SELECT organization_id, user_id, added_at, deleted_at
FROM organization_members
WHERE organization_id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetMemberByOrgAndUserParams struct {
	OrganizationID int64
	UserID         int64
}

type GetMemberByOrgAndUserRow struct {
	OrganizationID int64
	UserID         int64
	AddedAt        pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

func (q *Queries) GetMemberByOrgAndUser(ctx context.Context, arg GetMemberByOrgAndUserParams) (GetMemberByOrgAndUserRow, error) {
	row := q.db.QueryRow(ctx, getMemberByOrgAndUser, arg.OrganizationID, arg.UserID)
	var i GetMemberByOrgAndUserRow
	err := row.Scan(
		&i.OrganizationID,
		&i.UserID,
		&i.AddedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, organization_id, project_id, email, role, token, message, status, invited_by_user_id, accepted_by_user_id, created_at, expires_at, responded_at, deleted_at
FROM organization_invitations
WHERE organization_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetInvitationByIDParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) GetInvitationByID(ctx context.Context, arg GetInvitationByIDParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, arg.OrganizationID, arg.ID)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Message,
		&i.Status,
		&i.InvitedByUserID,
		&i.AcceptedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RespondedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvitationByTokenForUpdate = `-- name: GetInvitationByTokenForUpdate :one
SELECT id, organization_id, project_id, email, role, token, message, status, invited_by_user_id, accepted_by_user_id, created_at, expires_at, responded_at, deleted_at
FROM organization_invitations
WHERE token = $1
  AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetInvitationByTokenForUpdate(ctx context.Context, token string) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenForUpdate, token)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Message,
		&i.Status,
		&i.InvitedByUserID,
		&i.AcceptedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RespondedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, owner_user_id, created_at, deleted_at
FROM organizations
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertMemberRole = `-- name: InsertMemberRole :exec
INSERT INTO member_roles (organization_id, user_id, role)
SELECT $1, $2, $3
WHERE EXISTS (
  SELECT 1
  FROM organization_members m
  WHERE m.organization_id = $1
    AND m.user_id = $2
    AND m.deleted_at IS NULL
)
ON CONFLICT (organization_id, user_id, role) DO NOTHING
`

type InsertMemberRoleParams struct {
	OrganizationID int64
	UserID         int64
	Role           string
}

func (q *Queries) InsertMemberRole(ctx context.Context, arg InsertMemberRoleParams) error {
	_, err := q.db.Exec(ctx, insertMemberRole, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}

const listMemberRolesByOrgAndUser = `-- name: ListMemberRolesByOrgAndUser :many
SELECT role
FROM member_roles mr
WHERE mr.organization_id = $1
  AND mr.user_id = $2
  AND EXISTS (
    SELECT 1
    FROM organization_members m
    WHERE m.organization_id = $1
      AND m.user_id = $2
      AND m.deleted_at IS NULL
  )
ORDER BY role
`

type ListMemberRolesByOrgAndUserParams struct {
	OrganizationID int64
	UserID         int64
}

func (q *Queries) ListMemberRolesByOrgAndUser(ctx context.Context, arg ListMemberRolesByOrgAndUserParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listMemberRolesByOrgAndUser, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitationsByOrganization = `-- name: ListInvitationsByOrganization :many
SELECT id, organization_id, project_id, email, role, token, message, status, invited_by_user_id, accepted_by_user_id, created_at, expires_at, responded_at, deleted_at
FROM organization_invitations
WHERE organization_id = $1
  AND deleted_at IS NULL
ORDER BY id DESC
`

func (q *Queries) ListInvitationsByOrganization(ctx context.Context, organizationID int64) ([]OrganizationInvitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationInvitation
	for rows.Next() {
		var i OrganizationInvitation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.Message,
			&i.Status,
			&i.InvitedByUserID,
			&i.AcceptedByUserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RespondedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByOrganization = `-- name: ListTeamsByOrganization :many
SELECT id, organization_id, name, created_at, deleted_at
FROM teams
WHERE organization_id = $1
  AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListTeamsByOrganization(ctx context.Context, organizationID int64) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :one
UPDATE organization_invitations
SET status = 'accepted',
    accepted_by_user_id = $2,
    responded_at = $3
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, organization_id, project_id, email, role, token, message, status, invited_by_user_id, accepted_by_user_id, created_at, expires_at, responded_at, deleted_at
`

type MarkInvitationAcceptedParams struct {
	ID               int64
	AcceptedByUserID int64
	RespondedAt      pgtype.Timestamptz
}

func (q *Queries) MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, markInvitationAccepted, arg.ID, arg.AcceptedByUserID, arg.RespondedAt)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Message,
		&i.Status,
		&i.InvitedByUserID,
		&i.AcceptedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RespondedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markInvitationRefused = `-- name: MarkInvitationRefused :one
UPDATE organization_invitations
SET status = 'refused',
    accepted_by_user_id = $2,
    responded_at = $3
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, organization_id, project_id, email, role, token, message, status, invited_by_user_id, accepted_by_user_id, created_at, expires_at, responded_at, deleted_at
`

type MarkInvitationRefusedParams struct {
	ID               int64
	AcceptedByUserID int64
	RespondedAt      pgtype.Timestamptz
}

func (q *Queries) MarkInvitationRefused(ctx context.Context, arg MarkInvitationRefusedParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, markInvitationRefused, arg.ID, arg.AcceptedByUserID, arg.RespondedAt)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Message,
		&i.Status,
		&i.InvitedByUserID,
		&i.AcceptedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RespondedAt,
		&i.DeletedAt,
	)
	return i, err
}

const revokeInvitationByID = `-- name: RevokeInvitationByID :execrows
UPDATE organization_invitations
SET status = 'revoked',
    deleted_at = $3,
    responded_at = COALESCE(responded_at, $3)
WHERE organization_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type RevokeInvitationByIDParams struct {
	OrganizationID int64
	ID             int64
	DeletedAt      pgtype.Timestamptz
}

func (q *Queries) RevokeInvitationByID(ctx context.Context, arg RevokeInvitationByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitationByID, arg.OrganizationID, arg.ID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInvitationByID = `-- name: UpdateInvitationByID :one
UPDATE organization_invitations
SET email = $3,
    role = $4,
    message = $5,
    expires_at = $6
WHERE organization_id = $1
  AND id = $2
  AND status = 'pending'
  AND deleted_at IS NULL
RETURNING id, organization_id, project_id, email, role, token, message, status, invited_by_user_id, accepted_by_user_id, created_at, expires_at, responded_at, deleted_at
`

type UpdateInvitationByIDParams struct {
	OrganizationID int64
	ID             int64
	Email          string
	Role           string
	Message        string
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) UpdateInvitationByID(ctx context.Context, arg UpdateInvitationByIDParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, updateInvitationByID,
		arg.OrganizationID,
		arg.ID,
		arg.Email,
		arg.Role,
		arg.Message,
		arg.ExpiresAt,
	)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Message,
		&i.Status,
		&i.InvitedByUserID,
		&i.AcceptedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RespondedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertMember = `-- name: UpsertMember :exec
INSERT INTO organization_members (organization_id, user_id, added_at, deleted_at)
SELECT o.id, $2, $3, NULL
FROM organizations o
WHERE o.id = $1
  AND o.deleted_at IS NULL
ON CONFLICT (organization_id, user_id)
DO UPDATE SET added_at = EXCLUDED.added_at,
              deleted_at = NULL
`

type UpsertMemberParams struct {
	ID      int64
	UserID  int64
	AddedAt pgtype.Timestamptz
}

func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) error {
	_, err := q.db.Exec(ctx, upsertMember,
		arg.ID,
		arg.UserID,
		arg.AddedAt,
	)
	return err
}
