// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, owner_user_id, created_at)
VALUES ($1, $2, $3)
RETURNING id, name, owner_user_id, created_at
`

type CreateOrganizationParams struct {
	Name        string
	OwnerUserID int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.OwnerUserID, arg.CreatedAt)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (organization_id, name, created_at)
VALUES ($1, $2, $3)
RETURNING id, organization_id, name, created_at
`

type CreateTeamParams struct {
	OrganizationID int64
	Name           string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.OrganizationID, arg.Name, arg.CreatedAt)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberByOrgAndUser = `-- name: GetMemberByOrgAndUser :one
SELECT organization_id, user_id, COALESCE(team_id, 0) AS team_id, added_at
FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type GetMemberByOrgAndUserParams struct {
	OrganizationID int64
	UserID         int64
}

type GetMemberByOrgAndUserRow struct {
	OrganizationID int64
	UserID         int64
	TeamID         int64
	AddedAt        pgtype.Timestamptz
}

func (q *Queries) GetMemberByOrgAndUser(ctx context.Context, arg GetMemberByOrgAndUserParams) (GetMemberByOrgAndUserRow, error) {
	row := q.db.QueryRow(ctx, getMemberByOrgAndUser, arg.OrganizationID, arg.UserID)
	var i GetMemberByOrgAndUserRow
	err := row.Scan(
		&i.OrganizationID,
		&i.UserID,
		&i.TeamID,
		&i.AddedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, owner_user_id, created_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
	)
	return i, err
}

const insertMemberRole = `-- name: InsertMemberRole :exec
INSERT INTO member_roles (organization_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (organization_id, user_id, role) DO NOTHING
`

type InsertMemberRoleParams struct {
	OrganizationID int64
	UserID         int64
	Role           string
}

func (q *Queries) InsertMemberRole(ctx context.Context, arg InsertMemberRoleParams) error {
	_, err := q.db.Exec(ctx, insertMemberRole, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}

const listMemberRolesByOrgAndUser = `-- name: ListMemberRolesByOrgAndUser :many
SELECT role
FROM member_roles
WHERE organization_id = $1 AND user_id = $2
ORDER BY role
`

type ListMemberRolesByOrgAndUserParams struct {
	OrganizationID int64
	UserID         int64
}

func (q *Queries) ListMemberRolesByOrgAndUser(ctx context.Context, arg ListMemberRolesByOrgAndUserParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listMemberRolesByOrgAndUser, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByOrganization = `-- name: ListTeamsByOrganization :many
SELECT id, organization_id, name, created_at
FROM teams
WHERE organization_id = $1
ORDER BY id
`

func (q *Queries) ListTeamsByOrganization(ctx context.Context, organizationID int64) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMember = `-- name: UpsertMember :exec
INSERT INTO organization_members (organization_id, user_id, team_id, added_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (organization_id, user_id)
DO UPDATE SET team_id = EXCLUDED.team_id
`

type UpsertMemberParams struct {
	OrganizationID int64
	UserID         int64
	TeamID         pgtype.Int8
	AddedAt        pgtype.Timestamptz
}

func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) error {
	_, err := q.db.Exec(ctx, upsertMember,
		arg.OrganizationID,
		arg.UserID,
		arg.TeamID,
		arg.AddedAt,
	)
	return err
}
