// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	GetMemberByOrgAndUser(ctx context.Context, arg GetMemberByOrgAndUserParams) (GetMemberByOrgAndUserRow, error)
	GetOrganizationByID(ctx context.Context, id int64) (Organization, error)
	InsertMemberRole(ctx context.Context, arg InsertMemberRoleParams) error
	ListMemberRolesByOrgAndUser(ctx context.Context, arg ListMemberRolesByOrgAndUserParams) ([]string, error)
	ListTeamsByOrganization(ctx context.Context, organizationID int64) ([]Team, error)
	UpsertMember(ctx context.Context, arg UpsertMemberParams) error
}

var _ Querier = (*Queries)(nil)
