// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (OrganizationInvitation, error)
	GetInvitationByID(ctx context.Context, arg GetInvitationByIDParams) (OrganizationInvitation, error)
	GetInvitationByTokenForUpdate(ctx context.Context, token string) (OrganizationInvitation, error)
	GetOrganizationByID(ctx context.Context, id int64) (Organization, error)
	ListInvitationsByOrganization(ctx context.Context, organizationID int64) ([]OrganizationInvitation, error)
	MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) (OrganizationInvitation, error)
	MarkInvitationRefused(ctx context.Context, arg MarkInvitationRefusedParams) (OrganizationInvitation, error)
	RevokeInvitationByID(ctx context.Context, arg RevokeInvitationByIDParams) (int64, error)
	UpdateInvitationByID(ctx context.Context, arg UpdateInvitationByIDParams) (OrganizationInvitation, error)
}

var _ Querier = (*Queries)(nil)
