"use client";

import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useI18nScope } from "@/shared/hooks/use-i18n";

import { PromptDetailsSheet } from "../details/prompt-details-sheet";
import { PromptsFiltersToolbar } from "../filters/prompts-filters-toolbar";
import { PromptsPageHeader } from "../header/prompts-page-header";
import { PromptEditorPage } from "../editor/prompt-editor-page";
import { PromptsTabContent } from "../prompts/prompts-tab-content";
import { ResponseDetailsSheet } from "../details/response-details-sheet";
import { ResponsesTabContent } from "../response/responses-tab-content";
import { usePromptsWorkspacePanelViewModel } from "../../_lib/workspace/use-prompts-workspace-panel-view-model";
import type { PeriodKey, Persona, ResponseView } from "../../_lib/types";

type PromptsWorkspacePanelProps = {
  apiBaseURL: string;
  routeSearch: string;
};

export function PromptsWorkspacePanel({ apiBaseURL, routeSearch }: PromptsWorkspacePanelProps) {
  const content = useI18nScope("prompts-workspace");
  const state = usePromptsWorkspacePanelViewModel({ apiBaseURL, routeSearch });

  if (state.promptEditorState) {
    return (
      <PromptEditorPage
        mode={state.promptEditorState.mode}
        prompt={state.editorPrompt}
        availableModels={state.editorAvailableModels}
        getModelVisual={state.getModelVisual}
        saving={state.savingPromptEditor}
        onBack={state.closePromptEditor}
        onSave={state.saveCurrentPromptEditor}
      />
    );
  }

  return (
    <div className="flex h-full min-h-0 min-w-0 flex-col overflow-hidden md:p-4">
      <PromptsPageHeader
        activeCount={state.activePromptCount}
        activeCountLoading={state.promptsDataLoading}
        isDemo={state.mode === "demo"}
        generatingPrompts={state.generatingPrompts}
        onNewPrompt={state.openCreatePromptEditor}
        onAutoGenerate={state.addAutoGeneratedPrompts}
        onImportCsv={state.addImportedPrompts}
      />
      <div className="flex min-h-0 min-w-0 flex-1 flex-col md:rounded-md rounded-tr-none bg-background">
        <div className="border-b px-3 pb-3 md:px-4 md:pb-4">
          <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between md:gap-4">
            <div className="min-w-0 flex-1">
              <PromptsFiltersToolbar
                currentTab={state.tab}
                period={state.period}
                setPeriod={(value) => state.setPeriod(value as PeriodKey)}
                dateRange={state.dateRange}
                setDateRange={state.setDateRange}
                persona={state.persona}
                setPersona={(value) => state.setPersona(value as "all" | Persona)}
                availablePersonas={state.availablePersonas}
                search={state.search}
                setSearch={state.setSearch}
                showArchived={state.showArchived}
                setShowArchived={state.setShowArchived}
                hasActiveGlobalFilters={state.hasActiveGlobalFilters}
                clearFilters={state.clearFilters}
                modelsPopoverOpen={state.modelsPopoverOpen}
                setModelsPopoverOpen={state.setModelsPopoverOpen}
                allModelsSelected={state.allModelsSelected}
                selectedModels={state.selectedModels}
                availableModels={state.availableModels}
                modelsLoading={
                  state.tab === "responses"
                    ? state.responsesDataLoading
                    : state.promptsDataLoading
                }
                selectedCompetitors={state.selectedCompetitors}
                toggleCompetitor={state.toggleCompetitor}
                clearCompetitors={state.clearCompetitors}
                availableCompetitors={state.availableCompetitors}
                competitorsLoading={state.responsesDataLoading}
                getModelVisual={state.getModelVisual}
                toggleModel={state.toggleModel}
              />
            </div>
          </div>
        </div>

        <Tabs value={state.tab} onValueChange={(value) => state.setTab(value as "prompts" | "responses")} className="flex min-h-0 min-w-0 flex-1 flex-col">
          <div className="border-b px-3 py-3 md:px-4">
            <TabsList className="h-10 w-full md:w-auto space-x-2 p-1.5">
              <TabsTrigger value="prompts">{content.promptsTab}</TabsTrigger>
              <TabsTrigger value="responses">{content.responsesTab}</TabsTrigger>
            </TabsList>
          </div>

          <TabsContent value="prompts" className="m-0 flex min-h-0 min-w-0 flex-1">
            <PromptsTabContent
              filteredPrompts={state.filteredPrompts}
              promptsDataLoading={state.promptsDataLoading}
              promptsLoading={state.promptsLoading}
              hasPersonas={state.availablePersonas.length > 0}
              selectedPromptIds={state.selectedPromptIds}
              selectedPromptRows={state.selectedPromptRows}
              selectedPrompt={state.selectedPrompt}
              promptSort={state.promptSort}
              promptSortDirection={state.promptSortDirection}
              changePromptSort={state.changePromptSort}
              promptRowMode={state.promptRowMode}
              setPromptRowMode={state.setPromptRowMode}
              getPromptSelectionKey={state.getPromptSelectionKey}
              toggleSelectAllPrompts={state.toggleSelectAllPrompts}
              togglePromptSelection={state.togglePromptSelection}
              setSelectedPromptId={state.setSelectedPromptId}
              setIsPromptDetailsOpen={state.setIsPromptDetailsOpen}
              applyBulkStatus={state.applyBulkStatus}
              setFocusPromptId={state.setFocusPromptId}
              setTabResponses={() => state.setTab("responses")}
              deletePrompt={state.deletePrompt}
              deleteSelectedPrompts={state.deleteSelectedPrompts}
              onEditPrompt={state.openEditPromptEditor}
              canRunPrompt={state.canRunPrompt}
              runPrompt={state.runPrompt}
              isPromptRunning={state.isPromptRunning}
              canRunSelectedPrompts={state.canRunSelectedPrompts}
              selectedRunnablePromptCount={state.selectedRunnablePromptCount}
              runningSelectedPrompts={state.runningSelectedPrompts}
              runningAnyPrompts={state.runningAnyPrompts}
              runSelectedPrompts={state.runSelectedPrompts}
              getModelVisual={state.getModelVisual}
              rankTone={state.rankTone}
              statusBadgeClassName={state.statusBadgeClassName}
              onRunSelect={state.setSelectedResponseId}
              promptPage={state.promptPage}
              promptTotalItems={state.promptTotalItems}
              promptTotalPages={state.promptTotalPages}
              canPreviousPromptPage={state.canPreviousPromptPage}
              canNextPromptPage={state.canNextPromptPage}
              setPromptPage={state.setPromptPage}
            />
          </TabsContent>

          <TabsContent value="responses" className="m-0 flex min-h-0 flex-1 flex-col">
            <ResponsesTabContent
              noMentionOnly={state.noMentionOnly}
              setNoMentionOnly={state.setNoMentionOnly}
              showHistorical={state.showHistorical}
              setShowHistorical={state.setShowHistorical}
              loading={state.responsesDataLoading}
              viewMode={state.viewMode}
              setViewMode={(value) => state.setViewMode(value as ResponseView)}
              filteredResponses={state.filteredResponses}
              filteredResponsesTotal={state.filteredResponsesTotal}
              hasMoreResponses={state.hasMoreResponses}
              loadMoreResponses={state.loadMoreResponses}
              setSelectedResponseId={state.setSelectedResponseId}
              getModelVisual={state.getModelVisual}
              rankTone={state.rankTone}
              truncate={state.truncate}
            />
          </TabsContent>
        </Tabs>
      </div>

      <PromptDetailsSheet
        open={state.isPromptDetailsOpen}
        onOpenChange={state.setIsPromptDetailsOpen}
        prompt={state.selectedPrompt}
        getModelVisual={state.getModelVisual}
        onEditPrompt={(prompt) => state.openPromptDetailsEditor(prompt.sourcePromptId || prompt.id)}
        onSeeMoreResponses={(prompt) => state.showPromptResponses(prompt.sourcePromptId || prompt.id)}
        onOpenResponse={(prompt, responseId) =>
          state.showPromptResponse(prompt.sourcePromptId || prompt.id, responseId)
        }
      />
      <ResponseDetailsSheet
        response={state.selectedResponse}
        onOpenChange={(open) => !open && state.setSelectedResponseId(null)}
        getModelVisual={state.getModelVisual}
      />
    </div>
  );
}
