// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID        int64
	Channel   string
	Recipient string
	Subject   pgtype.Text
	Message   string
	CreatedAt pgtype.Timestamptz
}
