// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (channel, recipient, subject, message, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, channel, recipient, subject, message, created_at
`

type CreateNotificationParams struct {
	Channel   string
	Recipient string
	Subject   pgtype.Text
	Message   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.Channel,
		arg.Recipient,
		arg.Subject,
		arg.Message,
		arg.CreatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, channel, recipient, subject, message, created_at
FROM notifications
ORDER BY id DESC
LIMIT $1
`

func (q *Queries) ListNotifications(ctx context.Context, limit int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.Recipient,
			&i.Subject,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
