// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	ListNotifications(ctx context.Context, limit int32) ([]Notification, error)
}

var _ Querier = (*Queries)(nil)
