// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingSubscription struct {
	OrganizationID       int64
	Plan                 string
	Seats                int32
	MonthlyQuota         int32
	StripeCustomerID     string
	StripeSubscriptionID string
	StripePriceID        string
	BillingCycle         string
	Status               string
	CancelAtPeriodEnd    bool
	CurrentPeriodEnd     pgtype.Timestamptz
	CorrectionCredits    int32
	UpdatedAt            pgtype.Timestamptz
}

type BillingStripeWebhookEvent struct {
	EventID     string
	EventType   string
	ProcessedAt pgtype.Timestamptz
}
