// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingSubscription struct {
	OrganizationID int64
	Plan           string
	Seats          int32
	MonthlyQuota   int32
	UpdatedAt      pgtype.Timestamptz
}
