// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSubscriptionByOrganizationID = `-- name: GetSubscriptionByOrganizationID :one
SELECT organization_id, plan, seats, monthly_quota, updated_at
FROM billing_subscriptions
WHERE organization_id = $1
`

func (q *Queries) GetSubscriptionByOrganizationID(ctx context.Context, organizationID int64) (BillingSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByOrganizationID, organizationID)
	var i BillingSubscription
	err := row.Scan(
		&i.OrganizationID,
		&i.Plan,
		&i.Seats,
		&i.MonthlyQuota,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO billing_subscriptions (organization_id, plan, seats, monthly_quota, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (organization_id)
DO UPDATE SET
  plan = EXCLUDED.plan,
  seats = EXCLUDED.seats,
  monthly_quota = EXCLUDED.monthly_quota,
  updated_at = EXCLUDED.updated_at
`

type UpsertSubscriptionParams struct {
	OrganizationID int64
	Plan           string
	Seats          int32
	MonthlyQuota   int32
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertSubscription,
		arg.OrganizationID,
		arg.Plan,
		arg.Seats,
		arg.MonthlyQuota,
		arg.UpdatedAt,
	)
	return err
}
