package usecase

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
)

const (
	autoGeneratedMonitoringPromptCount = 10
	autoGeneratedMonitoringModelID     = "openai/gpt-oss-120b:free"
	autoGeneratedMonitoringProviderID  = "openrouter"
)

type generatedPromptsPayload struct {
	Prompts []string `json:"prompts"`
}

func stripMarkdownCodeFence(raw string) string {
	trimmed := strings.TrimSpace(raw)
	if !strings.HasPrefix(trimmed, "```") {
		return trimmed
	}

	lines := strings.Split(trimmed, "\n")
	if len(lines) == 0 {
		return trimmed
	}
	lines = lines[1:]
	if len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "```" {
		lines = lines[:len(lines)-1]
	}
	return strings.TrimSpace(strings.Join(lines, "\n"))
}

func parseGeneratedPromptTexts(raw string, expectedCount int) ([]string, error) {
	trimmed := stripMarkdownCodeFence(raw)
	if trimmed == "" {
		return nil, fmt.Errorf("%w: generated prompts response is empty", ErrValidation)
	}

	var prompts []string
	if err := json.Unmarshal([]byte(trimmed), &prompts); err == nil {
		return normalizeGeneratedPromptTexts(prompts, expectedCount)
	}

	var payload generatedPromptsPayload
	if err := json.Unmarshal([]byte(trimmed), &payload); err == nil {
		return normalizeGeneratedPromptTexts(payload.Prompts, expectedCount)
	}

	return nil, fmt.Errorf("%w: generated prompts response is not valid JSON", ErrValidation)
}

func normalizeGeneratedPromptTexts(prompts []string, expectedCount int) ([]string, error) {
	unique := make([]string, 0, len(prompts))
	seen := make(map[string]struct{}, len(prompts))

	for _, prompt := range prompts {
		trimmed := strings.TrimSpace(prompt)
		if trimmed == "" {
			continue
		}
		if _, ok := seen[trimmed]; ok {
			continue
		}
		seen[trimmed] = struct{}{}
		unique = append(unique, trimmed)
	}

	if len(unique) < expectedCount {
		return nil, fmt.Errorf(
			"%w: expected %d generated prompts, got %d",
			ErrValidation,
			expectedCount,
			len(unique),
		)
	}

	return unique[:expectedCount], nil
}

func buildMonitoringPromptGenerationInstruction(project Project, competitors []Competitor) string {
	builder := strings.Builder{}
	builder.WriteString("Generate exactly 10 realistic end-user prompts for AI search and recommendation analysis.\n")
	builder.WriteString("Return valid JSON only, with this shape: {\"prompts\":[\"...\", \"...\"]}.\n")
	builder.WriteString("Constraints:\n")
	builder.WriteString("- Exactly 10 prompts.\n")
	builder.WriteString("- Each prompt must be specific, natural, and realistic.\n")
	builder.WriteString("- Each prompt must sound like a real user asking for help in this sector.\n")
	builder.WriteString("- Adapt the prompts to the brand identity, positioning, offer, and target customer described in the context.\n")
	builder.WriteString("- Do not mention the brand, company name, product name, website, or any competitor name in the generated prompts.\n")
	builder.WriteString("- Do not ask explicitly to compare named companies or named products.\n")
	builder.WriteString("- Focus on category discovery, recommendation, use cases, pains, selection criteria, pricing expectations, integrations, onboarding, and switching considerations.\n")
	builder.WriteString("- Mix awareness, consideration, and decision intent.\n")
	builder.WriteString("- Write the prompts in French.\n")
	builder.WriteString("- Reflect the market, language, and buying context of the company when the context makes it clear.\n")
	builder.WriteString("- Use the business context only to understand the sector and target customer, not to mention the company.\n")
	builder.WriteString("- Do not number the prompts.\n")
	builder.WriteString("- Do not add explanations.\n")
	builder.WriteString("- Do not wrap the JSON in markdown.\n")
	builder.WriteString("\nBusiness context for sector and identity understanding only:\n")
	if description := strings.TrimSpace(project.BrandDescription); description != "" {
		builder.WriteString("Company description: ")
		builder.WriteString(description)
		builder.WriteString("\n")
	}
	if industry := strings.TrimSpace(project.Industry); industry != "" {
		builder.WriteString("Industry: ")
		builder.WriteString(industry)
		builder.WriteString("\n")
	}
	if primaryLanguage := strings.TrimSpace(project.PrimaryLanguage); primaryLanguage != "" {
		builder.WriteString("Primary language: ")
		builder.WriteString(primaryLanguage)
		builder.WriteString("\n")
	}
	if country := strings.TrimSpace(project.Country); country != "" {
		builder.WriteString("Primary market country: ")
		builder.WriteString(country)
		builder.WriteString("\n")
	}
	if attributionSource := strings.TrimSpace(project.AttributionSource); attributionSource != "" {
		builder.WriteString("Acquisition or attribution focus: ")
		builder.WriteString(attributionSource)
		builder.WriteString("\n")
	}
	if website := strings.TrimSpace(project.WebsiteURL); website != "" {
		builder.WriteString("Website: ")
		builder.WriteString(website)
		builder.WriteString("\n")
	}
	if len(competitors) > 0 {
		builder.WriteString("Competitive landscape exists, but do not mention competitor names in the prompts.\n")
	}

	return builder.String()
}

func (s *Service) GenerateMonitoringPrompts(ctx context.Context, projectID string, organizationID int64) ([]Prompt, error) {
	projectID = strings.TrimSpace(projectID)
	if organizationID <= 0 {
		return nil, fmt.Errorf("%w: organizationId must be positive", ErrValidation)
	}
	if s.iaClient == nil {
		return nil, fmt.Errorf("%w: ia client is unavailable", ErrDependencyUnavailable)
	}

	s.mu.Lock()
	if err := s.reloadLocked(ctx); err != nil {
		s.mu.Unlock()
		return nil, err
	}
	project, err := s.getProjectForOrganizationLocked(projectID, organizationID)
	if err != nil {
		s.mu.Unlock()
		return nil, err
	}

	competitors := make([]Competitor, 0)
	for _, competitor := range s.competitors {
		if competitor != nil && competitor.ProjectID == projectID && competitor.IsActive {
			competitors = append(competitors, copyCompetitor(competitor))
		}
	}

	providerAPIKey := ""
	if credentials := s.providerCredentials[projectID]; credentials != nil {
		if credential := credentials[autoGeneratedMonitoringProviderID]; credential != nil {
			providerAPIKey = strings.TrimSpace(credential.APIKey)
		}
	}
	projectCopy := s.effectiveProjectLocked(project)
	s.mu.Unlock()

	result, err := s.iaClient.ExecutePrompt(ctx, IAExecutePromptInput{
		PromptID:       "prompt-generator-monitoring",
		PromptText:     buildMonitoringPromptGenerationInstruction(projectCopy, competitors),
		ModelID:        autoGeneratedMonitoringModelID,
		ProviderID:     autoGeneratedMonitoringProviderID,
		ProviderAPIKey: providerAPIKey,
		PromptMode:     PromptModeOrganic,
	})
	if err != nil {
		return nil, err
	}

	generatedPrompts, err := parseGeneratedPromptTexts(result.RawResponse, autoGeneratedMonitoringPromptCount)
	if err != nil {
		return nil, err
	}

	return s.AddPromptsWithKind(ctx, projectID, organizationID, generatedPrompts, PromptKindMonitoring)
}
