#!/usr/bin/env python3

import argparse
import json
from pathlib import Path
import sys


REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "config" / "secrets.manifest.json"

GENERATED_FILES = {
    "makefile": REPO_ROOT / "config" / "secrets.generated.mk",
    "compose": REPO_ROOT / "docker-compose.secrets.generated.yml",
    "ansible": REPO_ROOT / "ansible" / "group_vars" / "generated_secrets.yml",
}


def load_manifest():
    data = json.loads(MANIFEST_PATH.read_text())
    secrets = data.get("secrets", [])
    seen = set()
    normalized = []
    for item in secrets:
        name = item["name"]
        if name in seen:
            raise ValueError(f"Duplicate secret in manifest: {name}")
        seen.add(name)
        normalized.append(
            {
                "name": name,
                "filename": f"{name}.txt",
                "required": bool(item.get("required", False)),
            }
        )
    return normalized


def render_makefile(secrets):
    required = [secret["filename"] for secret in secrets if secret["required"]]
    optional = [secret["filename"] for secret in secrets if not secret["required"]]
    return "\n".join(
        [
            "# Code generated by scripts/generate_secrets_config.py. DO NOT EDIT.",
            "",
            "REQUIRED_SECRETS := \\",
            *[f"\t{name} \\" for name in required[:-1]],
            f"\t{required[-1]}" if required else "",
            "",
            "OPTIONAL_SECRETS := \\",
            *[f"\t{name} \\" for name in optional[:-1]],
            f"\t{optional[-1]}" if optional else "",
            "",
        ]
    )


def render_compose(secrets):
    lines = ["# Code generated by scripts/generate_secrets_config.py. DO NOT EDIT.", "", "secrets:"]
    for secret in secrets:
        lines.append(f"  {secret['name']}:")
        lines.append(f"    file: ./secrets/{secret['filename']}")
    lines.append("")
    return "\n".join(lines)


def render_ansible(secrets):
    required = [secret["filename"] for secret in secrets if secret["required"]]
    optional = [secret["filename"] for secret in secrets if not secret["required"]]
    lines = ["# Code generated by scripts/generate_secrets_config.py. DO NOT EDIT.", ""]
    lines.append("docker_required_secret_files:")
    for name in required:
        lines.append(f"  - {name}")
    lines.append("")
    lines.append("docker_optional_secret_files:")
    for name in optional:
        lines.append(f"  - {name}")
    lines.append("")
    return "\n".join(lines)


def expected_outputs():
    secrets = load_manifest()
    return {
        GENERATED_FILES["makefile"]: render_makefile(secrets),
        GENERATED_FILES["compose"]: render_compose(secrets),
        GENERATED_FILES["ansible"]: render_ansible(secrets),
    }


def write_outputs():
    for path, content in expected_outputs().items():
        path.write_text(content)


def check_outputs():
    stale = []
    for path, expected in expected_outputs().items():
        actual = path.read_text() if path.exists() else None
        if actual != expected:
            stale.append(path)
    if stale:
        for path in stale:
            print(f"Out of date generated file: {path.relative_to(REPO_ROOT)}")
        return 1
    return 0


def main():
    parser = argparse.ArgumentParser(description="Generate secrets config from a single manifest.")
    parser.add_argument("--check", action="store_true", help="Fail if generated files are not up to date.")
    args = parser.parse_args()

    if args.check:
        return check_outputs()

    write_outputs()
    return 0


if __name__ == "__main__":
    sys.exit(main())
