auth:
  enabled: true
  existingSecret: infra-secrets
  existingSecretPasswordKey: redis_password
master:
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
