import type { PromptItem, Stage } from "./types";
import { defaultPromptSchedule, promptScheduleLabel } from "./utils";

export function buildAutoGeneratedPrompts(
  availableModels: string[],
  availablePersonas: string[],
  stages: Stage[],
): PromptItem[] {
  const topics = [
    "startup CRM",
    "sales pipeline",
    "onboarding flow",
    "pricing page",
    "SMB conversion",
    "B2B integrations",
    "security compliance",
    "customer success",
    "sales enablement",
    "lead scoring",
  ];
  const modelPool = availableModels.length > 0 ? availableModels : ["ChatGPT"];
  const personaPool = availablePersonas;

  return Array.from({ length: 50 }).map((_, index) => {
    const topic = topics[index % topics.length];
    const id = `auto-${Date.now()}-${index}`;
    const model = modelPool[index % modelPool.length];
    const stage = stages[index % stages.length];
    const personaValue = personaPool.length > 0 ? personaPool[index % personaPool.length] : undefined;
    const schedule = defaultPromptSchedule();
    return {
      id,
      sourcePromptId: id,
      rowMode: "global",
      prompt: `Auto ${index + 1} : meilleure strategie ${topic} ?`,
      stage,
      persona: personaValue,
      models: [model as never],
      schedule,
      effectiveCron: schedule.cron,
      effectiveScheduleLabel: promptScheduleLabel(schedule),
      effectiveScheduleSource: "global",
      mentionRate: Math.max(5, 70 - index),
      rank: 1 + (index % 6) * 0.7,
      sov: Math.max(4, 38 - (index % 10)),
      lastRunMinutes: 15 + index * 8,
      trend30d: [8, 11, 15, 19, 24, 28, 31],
      status: "active",
      runs: [],
    };
  });
}

export function buildImportedPrompts(): PromptItem[] {
  const stamp = Date.now();
  const firstId = `csv-${stamp}-1`;
  const secondId = `csv-${stamp}-2`;
  const firstSchedule = defaultPromptSchedule();
  const secondSchedule = defaultPromptSchedule();

  return [
    {
      id: firstId,
      sourcePromptId: firstId,
      rowMode: "global",
      prompt: "Outil CRM pour agences avec reporting multi-marques",
      stage: "Consideration",
      models: ["ChatGPT", "Perplexity"] as never,
      schedule: firstSchedule,
      effectiveCron: firstSchedule.cron,
      effectiveScheduleLabel: promptScheduleLabel(firstSchedule),
      effectiveScheduleSource: "global",
      mentionRate: 51,
      rank: 2.4,
      sov: 34,
      lastRunMinutes: 40,
      trend30d: [28, 31, 33, 39, 43, 47, 51],
      status: "active",
      runs: [],
    },
    {
      id: secondId,
      sourcePromptId: secondId,
      rowMode: "global",
      prompt: "Meilleur CRM pipeline avec SOC2 et SSO",
      stage: "Decision",
      models: ["Claude", "Gemini"] as never,
      schedule: secondSchedule,
      effectiveCron: secondSchedule.cron,
      effectiveScheduleLabel: promptScheduleLabel(secondSchedule),
      effectiveScheduleSource: "global",
      mentionRate: 62,
      rank: 1.7,
      sov: 45,
      lastRunMinutes: 80,
      trend30d: [31, 36, 40, 42, 47, 54, 62],
      status: "active",
      runs: [],
    },
  ];
}
