apiVersion: v1
kind: Service
metadata:
  name: kratos-public
  labels:
    app: kratos
spec:
  type: ClusterIP
  selector:
    app: kratos
  ports:
    - name: public
      port: 4433
      targetPort: public
