apiVersion: v1
kind: Service
metadata:
  name: kratos-admin
  labels:
    app: kratos
spec:
  type: ClusterIP
  selector:
    app: kratos
  ports:
    - name: admin
      port: 4434
      targetPort: admin
