// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             int64
	AuthIdentityID string
	Email          string
	FirstName      string
	LastName       string
	CreatedAt      pgtype.Timestamptz
}
