// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetUserByAuthIdentityID(ctx context.Context, authIdentityID string) (GetUserByAuthIdentityIDRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	RestoreUser(ctx context.Context, id int64) (int64, error)
	SetUserBanned(ctx context.Context, arg SetUserBannedParams) (int64, error)
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
