// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (auth_identity_id, email, first_name, last_name, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, auth_identity_id, email, first_name, last_name, created_at
`

type CreateUserParams struct {
	AuthIdentityID string
	Email          string
	FirstName      string
	LastName       string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.AuthIdentityID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthIdentityID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByAuthIdentityID = `-- name: GetUserByAuthIdentityID :one
SELECT id, auth_identity_id, email, first_name, last_name, created_at
FROM users
WHERE auth_identity_id = $1
`

func (q *Queries) GetUserByAuthIdentityID(ctx context.Context, authIdentityID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuthIdentityID, authIdentityID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthIdentityID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, auth_identity_id, email, first_name, last_name, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthIdentityID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}
