"use client";

import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CreatePromptDialog } from "./create-prompt-dialog";
import { PromptDetailsSheet } from "./prompt-details-sheet";
import { PromptModelsDialog } from "./prompt-models-dialog";
import { PromptScheduleDialog } from "./prompt-schedule-dialog";
import { PromptsFiltersToolbar } from "./prompts-filters-toolbar";
import { PromptsPageHeader } from "./prompts-page-header";
import { PromptsTabContent } from "./prompts-tab-content";
import { ResponseDetailsSheet } from "./response-details-sheet";
import { ResponsesTabContent } from "./responses-tab-content";
import { rankTone, statusBadgeVariant, truncate } from "./prompts-workspace-utils";
import { usePromptsResponsesState } from "./use-prompts-responses-state";
import { PeriodKey, Persona, ResponseView } from "./types";

type PromptsResponsesWorkspaceProps = {
  apiBaseURL: string;
};

export function PromptsResponsesWorkspace({ apiBaseURL }: PromptsResponsesWorkspaceProps) {
  const state = usePromptsResponsesState(apiBaseURL);
  const editingPrompt =
    state.prompts.find(
      (item) => (item.sourcePromptId || item.id) === state.editingPromptModelsId,
    ) ?? null;
  const editingSchedulePrompt =
    state.prompts.find(
      (item) => (item.sourcePromptId || item.id) === state.editingPromptScheduleId,
    ) ?? null;

  return (
    <div className="flex h-full min-h-0 flex-col overflow-hidden p-2 md:p-4">
      <PromptsPageHeader
        activeCount={state.prompts.filter((item) => item.status === "active").length}
        isDemo={state.mode === "demo"}
        onNewPrompt={() => state.setIsCreateOpen(true)}
        onAutoGenerate={state.addAutoGeneratedPrompts}
        onImportCsv={state.addImportedPrompts}
      />
      <div className="flex min-h-0 flex-1 flex-col rounded-md rounded-tr-none bg-background">
        <div className="border-b px-3 md:px-4 pb-3 md:pb-4">
          <PromptsFiltersToolbar
            period={state.period}
            setPeriod={(value) => state.setPeriod(value as PeriodKey)}
            dateRange={state.dateRange}
            setDateRange={state.setDateRange}
            persona={state.persona}
            setPersona={(value) => state.setPersona(value as "all" | Persona)}
            availablePersonas={state.availablePersonas}
            search={state.search}
            setSearch={state.setSearch}
            showArchived={state.showArchived}
            setShowArchived={state.setShowArchived}
            hasActiveGlobalFilters={state.hasActiveGlobalFilters}
            clearFilters={state.clearFilters}
            modelsPopoverOpen={state.modelsPopoverOpen}
            setModelsPopoverOpen={state.setModelsPopoverOpen}
            allModelsSelected={state.allModelsSelected}
            selectedModels={state.selectedModels}
            availableModels={state.availableModels}
            getModelVisual={state.getModelVisual}
            toggleModel={state.toggleModel}
          />
        </div>

        <Tabs value={state.tab} onValueChange={(value) => state.setTab(value as "prompts" | "responses")} className="flex min-h-0 flex-1 flex-col">
          <div className="border-b px-4 py-3">
            <TabsList>
              <TabsTrigger value="prompts">Prompts</TabsTrigger>
              <TabsTrigger value="responses">Responses</TabsTrigger>
            </TabsList>
          </div>

          <TabsContent value="prompts" className="m-0 flex min-h-0 flex-1">
            <PromptsTabContent
              filteredPrompts={state.filteredPrompts}
              promptsLoading={state.promptsLoading}
              hasPersonas={state.availablePersonas.length > 0}
              selectedPromptIds={state.selectedPromptIds}
              selectedPrompt={state.selectedPrompt}
              promptSort={state.promptSort}
              promptSortDirection={state.promptSortDirection}
              changePromptSort={state.changePromptSort}
              promptRowMode={state.promptRowMode}
              setPromptRowMode={state.setPromptRowMode}
              getPromptSelectionKey={state.getPromptSelectionKey}
              toggleSelectAllPrompts={state.toggleSelectAllPrompts}
              togglePromptSelection={state.togglePromptSelection}
              setSelectedPromptId={state.setSelectedPromptId}
              setIsPromptDetailsOpen={state.setIsPromptDetailsOpen}
              applyBulkStatus={state.applyBulkStatus}
              setFocusPromptId={state.setFocusPromptId}
              setTabResponses={() => state.setTab("responses")}
              deletePrompt={state.deletePrompt}
              onEditPromptModels={state.setEditingPromptModelsId}
              onEditPromptSchedule={state.setEditingPromptScheduleId}
              getModelVisual={state.getModelVisual}
              rankTone={rankTone}
              statusBadgeVariant={statusBadgeVariant}
              onRunSelect={state.setSelectedResponseId}
              promptPage={state.promptPage}
              promptTotalItems={state.promptTotalItems}
              promptTotalPages={state.promptTotalPages}
              canPreviousPromptPage={state.canPreviousPromptPage}
              canNextPromptPage={state.canNextPromptPage}
              setPromptPage={state.setPromptPage}
            />
          </TabsContent>

          <TabsContent value="responses" className="m-0 flex min-h-0 flex-1 flex-col">
            <ResponsesTabContent
              onlyErrors={state.onlyErrors}
              setOnlyErrors={state.setOnlyErrors}
              criticalOnly={state.criticalOnly}
              setCriticalOnly={state.setCriticalOnly}
              noMentionOnly={state.noMentionOnly}
              setNoMentionOnly={state.setNoMentionOnly}
              topCompetitor={state.topCompetitor}
              setTopCompetitor={state.setTopCompetitor}
              availableCompetitors={state.availableCompetitors}
              viewMode={state.viewMode}
              setViewMode={(value) => state.setViewMode(value as ResponseView)}
              filteredResponses={state.filteredResponses}
              filteredResponsesTotal={state.filteredResponsesTotal}
              hasMoreResponses={state.hasMoreResponses}
              loadMoreResponses={state.loadMoreResponses}
              setSelectedResponseId={state.setSelectedResponseId}
              getModelVisual={state.getModelVisual}
              rankTone={rankTone}
              truncate={truncate}
            />
          </TabsContent>
        </Tabs>
      </div>

      <CreatePromptDialog
        open={state.isCreateOpen}
        onOpenChange={state.setIsCreateOpen}
        formPrompt={state.formPrompt}
        setFormPrompt={state.setFormPrompt}
        formPersona={state.formPersona}
        setFormPersona={state.setFormPersona}
        formModels={state.formModels}
        setFormModels={state.setFormModels}
        availablePersonas={state.availablePersonas}
        availableModels={state.availableModels}
        getModelLabel={(model) => state.getModelVisual(model).label}
        onCreate={state.createPrompt}
      />

      <PromptModelsDialog
        open={!!state.editingPromptModelsId && !!editingPrompt}
        onOpenChange={(open) => !open && state.setEditingPromptModelsId(null)}
        promptLabel={editingPrompt?.prompt || ""}
        selectedModels={editingPrompt?.models || []}
        availableModels={state.availableModels}
        getModelVisual={state.getModelVisual}
        saving={state.updatingPromptModels}
        onSave={(models) => {
          if (!editingPrompt) return;
          state.updatePromptModels(editingPrompt.sourcePromptId || editingPrompt.id, models);
        }}
      />

      <PromptScheduleDialog
        open={!!state.editingPromptScheduleId && !!editingSchedulePrompt}
        onOpenChange={(open) => !open && state.setEditingPromptScheduleId(null)}
        promptLabel={editingSchedulePrompt?.prompt || ""}
        schedule={editingSchedulePrompt?.schedule || state.prompts[0]?.schedule || {
          mode: "global",
          cron: "0 */6 * * *",
          timezone: "UTC",
          modelCrons: {},
        }}
        selectedModels={editingSchedulePrompt?.models || []}
        getModelVisual={state.getModelVisual}
        saving={state.updatingPromptSchedule}
        onSave={(schedule) => {
          if (!editingSchedulePrompt) return;
          state.updatePromptSchedule(editingSchedulePrompt.sourcePromptId || editingSchedulePrompt.id, schedule);
        }}
      />

      <PromptDetailsSheet
        open={state.isPromptDetailsOpen}
        onOpenChange={state.setIsPromptDetailsOpen}
        prompt={state.selectedPrompt}
      />

      <ResponseDetailsSheet
        response={state.selectedResponse}
        onOpenChange={(open) => !open && state.setSelectedResponseId(null)}
      />
    </div>
  );
}
