"use client";

import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useI18nScope } from "@/shared/hooks/use-i18n";
import { PromptDetailsSheet } from "../components/prompt-details-sheet";
import { PromptsFiltersToolbar } from "../components/prompts-filters-toolbar";
import { PromptsPageHeader } from "../components/prompts-page-header";
import { PromptsPlanProgress } from "../components/prompts-plan-progress";
import { ResponseDetailsSheet } from "../components/response-details-sheet";
import { PromptEditorPage } from "./editor/prompt-editor-page";
import { PromptsTabContent } from "./list/prompts-tab-content";
import { ResponsesTabContent } from "./responses/responses-tab-content";
import { rankTone, statusBadgeVariant, truncate } from "../_lib/utils";
import { usePromptsResponsesState } from "../_lib/use-prompts-responses-state";
import type { PeriodKey, Persona, ResponseView } from "../_lib/types";

type PromptsResponsesWorkspaceProps = {
  apiBaseURL: string;
};

export function PromptsResponsesWorkspace({ apiBaseURL }: PromptsResponsesWorkspaceProps) {
  const content = useI18nScope("prompts-workspace");
  const state = usePromptsResponsesState(apiBaseURL);
  const editorPrompt =
    state.promptEditorState?.mode === "edit"
      ? state.prompts.find(
          (item) => (item.sourcePromptId || item.id) === state.promptEditorState?.promptId,
        ) ?? null
      : null;

  if (state.promptEditorState) {
    return (
      <PromptEditorPage
        mode={state.promptEditorState.mode}
        prompt={editorPrompt}
        availableModels={state.editorAvailableModels}
        getModelVisual={state.getModelVisual}
        saving={state.savingPromptEditor}
        onBack={state.closePromptEditor}
        onSave={({ text, modelIds, schedule, status }) =>
          state.savePromptEditor({
            mode: state.promptEditorState?.mode ?? "create",
            promptId: editorPrompt?.sourcePromptId || editorPrompt?.id,
            text,
            modelIds,
            schedule,
            status,
          })
        }
      />
    );
  }

  return (
    <div className="flex h-full min-h-0 min-w-0 flex-col overflow-hidden p-2 md:p-4">
      <PromptsPageHeader
        activeCount={state.prompts.filter((item) => item.status === "active").length}
        isDemo={state.mode === "demo"}
        onNewPrompt={state.openCreatePromptEditor}
        onAutoGenerate={state.addAutoGeneratedPrompts}
        onImportCsv={state.addImportedPrompts}
      />
      <div className="flex min-h-0 min-w-0 flex-1 flex-col rounded-md rounded-tr-none bg-background">
        <div className="border-b px-3 pb-3 md:px-4 md:pb-4">
          <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between md:gap-4">
            <div className="min-w-0 flex-1">
              <PromptsFiltersToolbar
                currentTab={state.tab}
                period={state.period}
                setPeriod={(value) => state.setPeriod(value as PeriodKey)}
                dateRange={state.dateRange}
                setDateRange={state.setDateRange}
                persona={state.persona}
                setPersona={(value) => state.setPersona(value as "all" | Persona)}
                availablePersonas={state.availablePersonas}
                search={state.search}
                setSearch={state.setSearch}
                showArchived={state.showArchived}
                setShowArchived={state.setShowArchived}
                hasActiveGlobalFilters={state.hasActiveGlobalFilters}
                clearFilters={state.clearFilters}
                modelsPopoverOpen={state.modelsPopoverOpen}
                setModelsPopoverOpen={state.setModelsPopoverOpen}
                allModelsSelected={state.allModelsSelected}
                selectedModels={state.selectedModels}
                availableModels={state.availableModels}
                getModelVisual={state.getModelVisual}
                toggleModel={state.toggleModel}
              />
            </div>
            <PromptsPlanProgress
              promptPlanUsage={state.promptPlanUsage}
              className="md:mb-1"
            />
          </div>
        </div>

        <Tabs value={state.tab} onValueChange={(value) => state.setTab(value as "prompts" | "responses")} className="flex min-h-0 min-w-0 flex-1 flex-col">
          <div className="border-b px-4 py-3">
            <TabsList>
              <TabsTrigger value="prompts">{content.promptsTab}</TabsTrigger>
              <TabsTrigger value="responses">{content.responsesTab}</TabsTrigger>
            </TabsList>
          </div>

          <TabsContent value="prompts" className="m-0 flex min-h-0 min-w-0 flex-1">
            <PromptsTabContent
              filteredPrompts={state.filteredPrompts}
              promptsLoading={state.promptsLoading}
              hasPersonas={state.availablePersonas.length > 0}
              selectedPromptIds={state.selectedPromptIds}
              selectedPrompt={state.selectedPrompt}
              promptSort={state.promptSort}
              promptSortDirection={state.promptSortDirection}
              changePromptSort={state.changePromptSort}
              promptRowMode={state.promptRowMode}
              setPromptRowMode={state.setPromptRowMode}
              getPromptSelectionKey={state.getPromptSelectionKey}
              toggleSelectAllPrompts={state.toggleSelectAllPrompts}
              togglePromptSelection={state.togglePromptSelection}
              setSelectedPromptId={state.setSelectedPromptId}
              setIsPromptDetailsOpen={state.setIsPromptDetailsOpen}
              applyBulkStatus={state.applyBulkStatus}
              setFocusPromptId={state.setFocusPromptId}
              setTabResponses={() => state.setTab("responses")}
              deletePrompt={state.deletePrompt}
              onEditPrompt={state.openEditPromptEditor}
              canRunPrompt={state.canRunPrompt}
              runPrompt={state.runPrompt}
              isPromptRunning={state.isPromptRunning}
              canRunSelectedPrompts={state.canRunSelectedPrompts}
              selectedRunnablePromptCount={state.selectedRunnablePromptCount}
              runningSelectedPrompts={state.runningSelectedPrompts}
              runningAnyPrompts={state.runningAnyPrompts}
              runSelectedPrompts={state.runSelectedPrompts}
              getModelVisual={state.getModelVisual}
              rankTone={rankTone}
              statusBadgeVariant={statusBadgeVariant}
              onRunSelect={state.setSelectedResponseId}
              promptPage={state.promptPage}
              promptTotalItems={state.promptTotalItems}
              promptTotalPages={state.promptTotalPages}
              canPreviousPromptPage={state.canPreviousPromptPage}
              canNextPromptPage={state.canNextPromptPage}
              setPromptPage={state.setPromptPage}
            />
          </TabsContent>

          <TabsContent value="responses" className="m-0 flex min-h-0 flex-1 flex-col">
            <ResponsesTabContent
              onlyErrors={state.onlyErrors}
              setOnlyErrors={state.setOnlyErrors}
              criticalOnly={state.criticalOnly}
              setCriticalOnly={state.setCriticalOnly}
              noMentionOnly={state.noMentionOnly}
              setNoMentionOnly={state.setNoMentionOnly}
              showHistorical={state.showHistorical}
              setShowHistorical={state.setShowHistorical}
              selectedCompetitors={state.selectedCompetitors}
              toggleCompetitor={state.toggleCompetitor}
              clearCompetitors={state.clearCompetitors}
              availableCompetitors={state.availableCompetitors}
              viewMode={state.viewMode}
              setViewMode={(value) => state.setViewMode(value as ResponseView)}
              filteredResponses={state.filteredResponses}
              filteredResponsesTotal={state.filteredResponsesTotal}
              hasMoreResponses={state.hasMoreResponses}
              loadMoreResponses={state.loadMoreResponses}
              setSelectedResponseId={state.setSelectedResponseId}
              getModelVisual={state.getModelVisual}
              rankTone={rankTone}
              truncate={truncate}
            />
          </TabsContent>
        </Tabs>
      </div>

      <PromptDetailsSheet open={state.isPromptDetailsOpen} onOpenChange={state.setIsPromptDetailsOpen} prompt={state.selectedPrompt} />
      <ResponseDetailsSheet response={state.selectedResponse} onOpenChange={(open) => !open && state.setSelectedResponseId(null)} />
    </div>
  );
}
