"use client";

import { useDeferredValue, useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { DateRange } from "react-day-picker";
import { differenceInCalendarDays } from "date-fns";
import { useDashboardData } from "@/hooks/use-dashboard-data";
import { apiRoutes } from "@/lib/api-config";
import { appQueryKeys } from "@/lib/query-keys";
import { toSafeImageAssetPath } from "@/lib/safe-asset-path";
import { gatewayJSON } from "@/shared/api/gateway";
import { SELECTED_ORG_KEY } from "@/features/models/core/model-access";
import {
  PERIOD_TO_MINUTES,
  STAGES,
  normalizeModelName,
} from "./prompts-workspace-utils";
import {
  AIModel,
  ModelVisual,
  PeriodKey,
  Persona,
  PromptItem,
  PromptRowMode,
  PromptSort,
  PromptSortDirection,
  ResponseView,
} from "./types";
import {
  buildAutoGeneratedPrompts,
  buildImportedPrompts,
  buildPromptPageItems,
  buildResponseRows,
} from "./prompt-data-factory";

const PROMPTS_PAGE_SIZE = 25;
const PROMPTS_CATALOG_PAGE_SIZE = 100;
const RESPONSES_BATCH_SIZE = 40;

const PROMPT_SORT_DEFAULT_DIRECTION: Record<PromptSort, PromptSortDirection> = {
  prompt: "asc",
  persona: "asc",
  ai: "asc",
  mention: "desc",
  rank: "asc",
  sov: "desc",
  lastRun: "asc",
  status: "asc",
};

const PROMPT_STATUS_ORDER: Record<PromptItem["status"], number> = {
  active: 0,
  disabled: 1,
  archived: 2,
};

type ProjectPromptRecord = {
  id: string;
  text: string;
  intent?: string;
  isActive: boolean;
  createdAt?: string;
  updatedAt?: string;
};

type PromptPageResult = {
  items: ProjectPromptRecord[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNext: boolean;
  hasPrevious: boolean;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function getField<T = unknown>(obj: Record<string, unknown>, keys: string[]): T | undefined {
  for (const key of keys) {
    if (key in obj) return obj[key] as T;
  }
  return undefined;
}

function unwrapSuccessEnvelope(value: unknown): unknown {
  if (!isRecord(value)) return value;
  if (value.success === true && "data" in value) {
    return value.data;
  }
  return value;
}

function getString(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function getBool(value: unknown): boolean {
  return value === true;
}

function getNumber(value: unknown): number {
  return typeof value === "number" && Number.isFinite(value) ? value : 0;
}

function readSelectedOrganizationId(): string {
  if (typeof window === "undefined") return "";
  try {
    return window.localStorage.getItem(SELECTED_ORG_KEY)?.trim() ?? "";
  } catch {
    return "";
  }
}

function normalizePromptPage(value: unknown): PromptPageResult {
  const payload = unwrapSuccessEnvelope(value);
  const record = isRecord(payload) ? payload : {};
  const rawItems = Array.isArray(payload)
    ? payload
    : Array.isArray(record.items)
      ? record.items
      : [];
  const items = rawItems
    .filter((entry): entry is Record<string, unknown> => isRecord(entry))
    .map((entry) => ({
      id: getString(getField(entry, ["id", "ID"])),
      text: getString(getField(entry, ["text", "Text"])),
      intent: getString(getField(entry, ["intent", "Intent"])) || undefined,
      isActive: getBool(getField(entry, ["isActive", "IsActive"])),
      createdAt: getString(getField(entry, ["createdAt", "CreatedAt"])) || undefined,
      updatedAt: getString(getField(entry, ["updatedAt", "UpdatedAt"])) || undefined,
    }))
    .filter((item) => item.id !== "" && item.text !== "");
  const isLegacyArray = Array.isArray(payload);
  const total = isLegacyArray ? items.length : getNumber(getField(record, ["total", "Total"]));
  const page = isLegacyArray ? 1 : Math.max(1, getNumber(getField(record, ["page", "Page"])) || 1);
  const pageSize = isLegacyArray
    ? Math.max(items.length, PROMPTS_PAGE_SIZE)
    : Math.max(1, getNumber(getField(record, ["pageSize", "PageSize"])) || PROMPTS_PAGE_SIZE);
  const totalPages = isLegacyArray
    ? (items.length > 0 ? 1 : 0)
    : Math.max(0, getNumber(getField(record, ["totalPages", "TotalPages"])));
  const hasNext = isLegacyArray ? false : getBool(getField(record, ["hasNext", "HasNext"]));
  const hasPrevious = isLegacyArray ? false : getBool(getField(record, ["hasPrevious", "HasPrevious"]));

  return {
    items,
    total,
    page,
    pageSize,
    totalPages,
    hasNext,
    hasPrevious,
  };
}

async function loadPromptPage(
  apiBaseURL: string,
  organizationId: string,
  projectId: string,
  page: number,
  pageSize: number,
  search: string,
  signal?: AbortSignal,
): Promise<PromptPageResult> {
  const response = await gatewayJSON<unknown>(
    apiBaseURL,
    apiRoutes.projects.prompts(projectId, { page, pageSize, search }),
    {
      method: "GET",
      organizationId,
      signal,
    },
  );

  if (!response.ok) {
    throw new Error("Impossible de charger les prompts.");
  }

  return normalizePromptPage(response.data);
}

async function loadAllPromptPages(
  apiBaseURL: string,
  organizationId: string,
  projectId: string,
  search: string,
  signal?: AbortSignal,
): Promise<ProjectPromptRecord[]> {
  const firstPage = await loadPromptPage(
    apiBaseURL,
    organizationId,
    projectId,
    1,
    PROMPTS_CATALOG_PAGE_SIZE,
    search,
    signal,
  );

  if (firstPage.totalPages <= 1) {
    return firstPage.items;
  }

  const remainingPages = await Promise.all(
    Array.from({ length: firstPage.totalPages - 1 }, (_, index) =>
      loadPromptPage(
        apiBaseURL,
        organizationId,
        projectId,
        index + 2,
        PROMPTS_CATALOG_PAGE_SIZE,
        search,
        signal,
      ),
    ),
  );

  return [firstPage, ...remainingPages].flatMap((page) => page.items);
}

function compareStrings(a: string, b: string): number {
  return a.localeCompare(b, "fr", { sensitivity: "base", numeric: true });
}

function comparePromptItems(a: PromptItem, b: PromptItem, field: PromptSort): number {
  if (field === "prompt") return compareStrings(a.prompt, b.prompt);

  if (field === "persona") {
    return compareStrings(a.persona?.trim() || "\uffff", b.persona?.trim() || "\uffff");
  }

  if (field === "ai") {
    const aModels = a.models.map((model) => normalizeModelName(model)).join("|");
    const bModels = b.models.map((model) => normalizeModelName(model)).join("|");
    return compareStrings(aModels || "\uffff", bModels || "\uffff");
  }

  if (field === "mention") return a.mentionRate - b.mentionRate;
  if (field === "rank") return a.rank - b.rank;
  if (field === "sov") return a.sov - b.sov;
  if (field === "lastRun") return a.lastRunMinutes - b.lastRunMinutes;

  if (field === "status") {
    return PROMPT_STATUS_ORDER[a.status] - PROMPT_STATUS_ORDER[b.status];
  }

  return compareStrings(a.prompt, b.prompt);
}

function sortPromptItems(
  rows: PromptItem[],
  field: PromptSort,
  direction: PromptSortDirection,
): PromptItem[] {
  const multiplier = direction === "asc" ? 1 : -1;

  return [...rows].sort((a, b) => {
    const primary = comparePromptItems(a, b, field);
    if (primary !== 0) return primary * multiplier;
    return compareStrings(a.prompt, b.prompt);
  });
}

function buildModelScopedPromptRows(prompts: PromptItem[]): PromptItem[] {
  return prompts.flatMap((prompt) => {
    const sourcePromptId = prompt.sourcePromptId || prompt.id;
    const runsByModel = prompt.runs.reduce((map, run) => {
      const bucket = map.get(run.model) ?? [];
      bucket.push(run);
      map.set(run.model, bucket);
      return map;
    }, new Map<string, typeof prompt.runs>());

    const models = runsByModel.size > 0 ? Array.from(runsByModel.keys()) : prompt.models;

    return models.map((model, index) => {
      const runs = [...(runsByModel.get(model) ?? [])].sort((a, b) => a.minutesAgo - b.minutesAgo);
      const mentionRate =
        runs.length > 0
          ? Math.round((runs.filter((item) => item.mention).length / runs.length) * 100)
          : 0;
      const rankedRuns = runs.filter((item) => typeof item.rank === "number");
      const rank =
        rankedRuns.length > 0
          ? Number(
              (
                rankedRuns.reduce((sum, item) => sum + (item.rank ?? 0), 0) / rankedRuns.length
              ).toFixed(1),
            )
          : 9.9;
      const sov =
        runs.length > 0
          ? Math.round(runs.reduce((sum, item) => sum + item.score, 0) / runs.length)
          : 0;
      const lastRunMinutes =
        runs.length > 0
          ? Math.min(...runs.map((item) => item.minutesAgo))
          : prompt.lastRunMinutes;
      const trendSeed = runs.slice(0, 7).map((item) => item.score);
      const trend30d =
        trendSeed.length > 0
          ? Array.from(
              { length: 7 },
              (_, trendIndex) => trendSeed[trendIndex] ?? trendSeed[trendSeed.length - 1] ?? 0,
            )
          : prompt.trend30d;

      return {
        ...prompt,
        id: `${sourcePromptId}::${normalizeModelName(model) || index}`,
        sourcePromptId,
        rowMode: "model" as PromptRowMode,
        models: model ? [model] : [],
        mentionRate,
        rank,
        sov,
        lastRunMinutes,
        trend30d,
        runs,
      };
    });
  });
}

export function usePromptsResponsesState(apiBaseURL: string) {
  const { data: dashboardData, mode, projectId } = useDashboardData();
  const activeProjectId = projectId || dashboardData.project.id || "";
  const liveModels = useMemo(() => dashboardData.models.filter((item) => item.live), [dashboardData.models]);
  const modelMeta = useMemo(() => {
    const map = new Map<string, { icon: string; description: string; label: string }>();
    for (const model of liveModels) {
      const keys = [
        model.providerModelId,
        model.groupName,
        model.displayName,
        model.id,
      ]
        .map((value) => normalizeModelName(value))
        .filter(Boolean);
      const entry = {
        icon: toSafeImageAssetPath(model.iconPath),
        description: model.displayName,
        label: model.groupName || model.displayName,
      };
      for (const key of keys) {
        map.set(key, entry);
      }
    }
    return map;
  }, [liveModels]);

  const getModelVisual = (model: string): ModelVisual =>
    modelMeta.get(normalizeModelName(model)) || {
      icon: "/models/openai.svg",
      description: "AI model",
      label: model,
    };

  const availableModels = useMemo(() => liveModels.map((item) => item.providerModelId), [liveModels]);
  const availablePersonas = useMemo(
    () =>
      Array.from(
        new Set(
          dashboardData.recent_prompts
            .map((item) => item.persona?.trim() || "")
            .filter(Boolean),
        ),
      ),
    [dashboardData.recent_prompts],
  );
  const availableCompetitors = useMemo(
    () => dashboardData.project.competitors.map((item) => item.name),
    [dashboardData.project.competitors],
  );

  const [organizationId, setOrganizationId] = useState("");
  const [period, setPeriod] = useState<PeriodKey>("7d");
  const [dateRange, setDateRange] = useState<DateRange | undefined>(undefined);
  const [tab, setTab] = useState<"prompts" | "responses">("prompts");
  const [persona, setPersona] = useState<"all" | Persona>("all");
  const [search, setSearch] = useState("");
  const deferredSearch = useDeferredValue(search.trim());
  const [selectedModels, setSelectedModels] = useState<AIModel[]>([]);
  const [promptSort, setPromptSort] = useState<PromptSort>("mention");
  const [promptSortDirection, setPromptSortDirection] = useState<PromptSortDirection>("desc");
  const [viewMode, setViewMode] = useState<ResponseView>("table");
  const [onlyErrors, setOnlyErrors] = useState(false);
  const [criticalOnly, setCriticalOnly] = useState(false);
  const [noMentionOnly, setNoMentionOnly] = useState(false);
  const [topCompetitor, setTopCompetitor] = useState<"all" | string>("all");
  const [selectedPromptIds, setSelectedPromptIds] = useState<string[]>([]);
  const [selectedPromptId, setSelectedPromptId] = useState<string | null>(null);
  const [isPromptDetailsOpen, setIsPromptDetailsOpen] = useState(false);
  const [selectedResponseId, setSelectedResponseId] = useState<string | null>(null);
  const [focusPromptId, setFocusPromptId] = useState<string | null>(null);
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [manualPrompts, setManualPrompts] = useState<PromptItem[]>([]);
  const [formPrompt, setFormPrompt] = useState("");
  const [formPersona, setFormPersona] = useState<Persona>("");
  const [formModel, setFormModel] = useState<AIModel>("");
  const [modelsPopoverOpen, setModelsPopoverOpen] = useState(false);
  const [promptPage, setPromptPage] = useState(1);
  const [promptRowMode, setPromptRowMode] = useState<PromptRowMode>("global");
  const [responseVisibleCount, setResponseVisibleCount] = useState(RESPONSES_BATCH_SIZE);
  const [promptStatusOverrides, setPromptStatusOverrides] = useState<Record<string, PromptItem["status"]>>({});
  const [hiddenPromptIds, setHiddenPromptIds] = useState<string[]>([]);

  useEffect(() => {
    setOrganizationId(readSelectedOrganizationId());
  }, []);

  const promptsCatalogQuery = useQuery<ProjectPromptRecord[]>({
    queryKey: appQueryKeys.promptsCatalog(
      apiBaseURL,
      organizationId,
      activeProjectId,
      deferredSearch,
      promptSort,
      promptSortDirection,
    ),
    enabled: apiBaseURL.trim() !== "" && organizationId !== "" && activeProjectId !== "",
    placeholderData: (previous) => previous,
    queryFn: ({ signal }) =>
      loadAllPromptPages(
        apiBaseURL,
        organizationId,
        activeProjectId,
        deferredSearch,
        signal,
      ),
  });

  useEffect(() => {
    setPromptPage(1);
  }, [
    deferredSearch,
    period,
    dateRange?.from?.toISOString(),
    dateRange?.to?.toISOString(),
    persona,
    selectedModels.join("|"),
    promptRowMode,
    promptSort,
    promptSortDirection,
  ]);

  useEffect(() => {
    if (availableModels.length === 0) return;
    setSelectedModels((current) => {
      const kept = current.filter((model) => availableModels.includes(model));
      if (kept.length > 0) return kept;
      return availableModels;
    });
    setFormModel((current) => (availableModels.includes(current) ? current : availableModels[0]));
    setFormPersona((current) => (availablePersonas.includes(current) ? current : availablePersonas[0] || ""));
  }, [availableModels, availablePersonas]);

  const serverPromptItems = useMemo(
    () =>
      buildPromptPageItems({
        projectPrompts: promptsCatalogQuery.data ?? [],
        recentPrompts: dashboardData.recent_prompts,
        competitors: dashboardData.project.competitors,
        availableModels,
        stages: STAGES,
      }),
    [
      promptsCatalogQuery.data,
      dashboardData.recent_prompts,
      dashboardData.project.competitors,
      availableModels,
    ],
  );

  const basePrompts = useMemo(() => {
    const searchLower = deferredSearch.toLowerCase();
    const visibleManualPrompts = manualPrompts.filter((item) =>
      searchLower === "" ? true : item.prompt.toLowerCase().includes(searchLower),
    );
    const merged = [...visibleManualPrompts, ...serverPromptItems];
    return merged
      .filter((item) => !hiddenPromptIds.includes(item.sourcePromptId || item.id))
      .map((item) => {
        const nextStatus = promptStatusOverrides[item.sourcePromptId || item.id];
        return nextStatus ? { ...item, status: nextStatus } : item;
      });
  }, [deferredSearch, hiddenPromptIds, manualPrompts, promptStatusOverrides, serverPromptItems]);

  const prompts = useMemo(
    () => (promptRowMode === "global" ? basePrompts : buildModelScopedPromptRows(basePrompts)),
    [basePrompts, promptRowMode],
  );

  const allResponses = useMemo(
    () =>
      buildResponseRows({
        recentPrompts: dashboardData.recent_prompts,
        competitors: dashboardData.project.competitors,
        availableModels,
        stages: STAGES,
      }),
    [availableModels, dashboardData.project.competitors, dashboardData.recent_prompts],
  );

  const rangeMinutes = useMemo(() => {
    if (period !== "custom") return PERIOD_TO_MINUTES[period];
    if (!dateRange?.from) return PERIOD_TO_MINUTES["90d"];
    const to = dateRange.to ?? dateRange.from;
    const days = Math.max(1, differenceInCalendarDays(to, dateRange.from) + 1);
    return days * 24 * 60;
  }, [dateRange, period]);

  const filteredPromptRows = useMemo(() => {
    const searchLower = deferredSearch.toLowerCase();
    const rows = prompts.filter((item) => {
      const matchesPeriod = item.lastRunMinutes <= rangeMinutes || item.runs.length === 0;
      const matchesModel =
        selectedModels.length === 0 || item.models.length === 0 || item.models.some((model) => selectedModels.includes(model));
      const matchesPersona = persona === "all" || item.persona === persona;
      const matchesSearch = searchLower === "" || item.prompt.toLowerCase().includes(searchLower);
      return matchesPeriod && matchesModel && matchesPersona && matchesSearch;
    });

    return sortPromptItems(rows, promptSort, promptSortDirection);
  }, [deferredSearch, persona, promptSort, promptSortDirection, prompts, rangeMinutes, selectedModels]);

  const promptTotalItems = filteredPromptRows.length;
  const promptTotalPages = Math.max(1, Math.ceil(promptTotalItems / PROMPTS_PAGE_SIZE));

  useEffect(() => {
    if (promptPage > promptTotalPages) {
      setPromptPage(promptTotalPages);
    }
  }, [promptPage, promptTotalPages]);

  const filteredPrompts = useMemo(() => {
    const start = (promptPage - 1) * PROMPTS_PAGE_SIZE;
    return filteredPromptRows.slice(start, start + PROMPTS_PAGE_SIZE);
  }, [filteredPromptRows, promptPage]);

  const filteredResponses = useMemo(() => {
    const searchLower = search.toLowerCase().trim();
    return allResponses
      .filter((item) => {
        const matchesPeriod = item.minutesAgo <= rangeMinutes;
        const matchesModel = selectedModels.length === 0 || selectedModels.includes(item.model);
        const matchesPersona = persona === "all" || item.persona === persona;
        const matchesSearch = searchLower.length === 0 || item.prompt.toLowerCase().includes(searchLower);
        const matchesError = !onlyErrors || Boolean(item.error);
        const matchesCritical = !criticalOnly || item.critical;
        const matchesNoMention = !noMentionOnly || !item.mention;
        const matchesCompetitor = topCompetitor === "all" || item.competitor === topCompetitor;
        const matchesFocusedPrompt = !focusPromptId || item.promptId === focusPromptId;
        return (
          matchesPeriod &&
          matchesModel &&
          matchesPersona &&
          matchesSearch &&
          matchesError &&
          matchesCritical &&
          matchesNoMention &&
          matchesCompetitor &&
          matchesFocusedPrompt
        );
      })
      .sort((a, b) => a.minutesAgo - b.minutesAgo);
  }, [
    allResponses,
    criticalOnly,
    focusPromptId,
    noMentionOnly,
    onlyErrors,
    rangeMinutes,
    persona,
    search,
    selectedModels,
    topCompetitor,
  ]);

  useEffect(() => {
    const selectablePromptIds = new Set(filteredPromptRows.map((item) => item.sourcePromptId || item.id));
    setSelectedPromptIds((current) => current.filter((id) => selectablePromptIds.has(id)));
    setSelectedPromptId((current) =>
      current && filteredPromptRows.some((item) => item.id === current) ? current : filteredPromptRows[0]?.id ?? null,
    );
  }, [filteredPromptRows]);

  useEffect(() => {
    setResponseVisibleCount(RESPONSES_BATCH_SIZE);
  }, [
    criticalOnly,
    dateRange?.from?.toISOString(),
    dateRange?.to?.toISOString(),
    focusPromptId,
    noMentionOnly,
    onlyErrors,
    period,
    persona,
    search,
    selectedModels.join("|"),
    topCompetitor,
  ]);

  useEffect(() => {
    setResponseVisibleCount((current) => Math.min(Math.max(RESPONSES_BATCH_SIZE, current), filteredResponses.length || RESPONSES_BATCH_SIZE));
  }, [filteredResponses.length]);

  const visibleResponses = useMemo(
    () => filteredResponses.slice(0, responseVisibleCount),
    [filteredResponses, responseVisibleCount],
  );

  const selectedPrompt = filteredPromptRows.find((item) => item.id === selectedPromptId) ?? null;
  const selectedResponse = allResponses.find((item) => item.id === selectedResponseId) ?? null;
  const allModelsSelected =
    availableModels.length > 0 &&
    selectedModels.length === availableModels.length &&
    availableModels.every((model) => selectedModels.includes(model));

  const hasActiveGlobalFilters =
    period !== "7d" ||
    persona !== "all" ||
    search.trim().length > 0 ||
    selectedModels.length !== availableModels.length ||
    availableModels.some((model) => !selectedModels.includes(model));

  const clearFilters = () => {
    setPeriod("7d");
    setDateRange(undefined);
    setSelectedModels(availableModels);
    setPersona("all");
    setSearch("");
    setOnlyErrors(false);
    setCriticalOnly(false);
    setNoMentionOnly(false);
    setTopCompetitor("all");
    setFocusPromptId(null);
    setPromptPage(1);
  };

  const toggleModel = (model: AIModel) => {
    if (allModelsSelected) {
      setSelectedModels([model]);
      return;
    }
    setSelectedModels((prev) => (prev.includes(model) ? prev.filter((item) => item !== model) : [...prev, model]));
  };

  const togglePromptSelection = (id: string) => {
    setSelectedPromptIds((prev) => (prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]));
  };

  const toggleSelectAllPrompts = (checked: boolean) => {
    if (!checked) {
      setSelectedPromptIds([]);
      return;
    }
    setSelectedPromptIds(
      Array.from(new Set(filteredPrompts.map((item) => item.sourcePromptId || item.id))),
    );
  };

  const changePromptSort = (nextSort: PromptSort) => {
    if (promptSort === nextSort) {
      setPromptSortDirection((current) => (current === "asc" ? "desc" : "asc"));
      return;
    }

    setPromptSort(nextSort);
    setPromptSortDirection(PROMPT_SORT_DEFAULT_DIRECTION[nextSort]);
  };

  const applyBulkStatus = (status: PromptItem["status"]) => {
    if (selectedPromptIds.length === 0) return;
    setManualPrompts((prev) =>
      prev.map((item) =>
        selectedPromptIds.includes(item.sourcePromptId || item.id) ? { ...item, status } : item,
      ),
    );
    setPromptStatusOverrides((prev) => {
      const next = { ...prev };
      for (const id of selectedPromptIds) {
        next[id] = status;
      }
      return next;
    });
  };

  const createPrompt = () => {
    if (!formPrompt.trim()) return;
    const nextId = `p${Date.now()}`;
    const newPrompt: PromptItem = {
      id: nextId,
      sourcePromptId: nextId,
      rowMode: "global",
      prompt: formPrompt.trim(),
      stage: "Awareness",
      persona: formPersona || undefined,
      models: formModel ? [formModel] : [],
      mentionRate: 0,
      rank: 9.9,
      sov: 0,
      lastRunMinutes: 1,
      trend30d: [0, 0, 0, 0, 0, 0, 0],
      status: "active",
      runs: [],
    };
    setManualPrompts((prev) => [newPrompt, ...prev]);
    setPromptPage(1);
    setFormPrompt("");
    setFormPersona(availablePersonas[0] || "");
    setFormModel(availableModels[0] || "");
    setIsCreateOpen(false);
  };

  const addAutoGeneratedPrompts = () => {
    setManualPrompts((prev) => [...buildAutoGeneratedPrompts(availableModels, availablePersonas, STAGES), ...prev]);
    setPromptPage(1);
  };

  const addImportedPrompts = () => {
    const imported = buildImportedPrompts();
    setManualPrompts((prev) => [...imported, ...prev]);
    setPromptPage(1);
  };

  const deletePrompt = (id: string) => {
    let removedManual = false;
    setManualPrompts((prev) => {
      const next = prev.filter((item) => (item.sourcePromptId || item.id) !== id);
      removedManual = next.length !== prev.length;
      return next;
    });
    if (!removedManual) {
      setHiddenPromptIds((prev) => (prev.includes(id) ? prev : [...prev, id]));
    }
    setSelectedPromptIds((prev) => prev.filter((item) => item !== id));
    if (selectedPromptId === id) setSelectedPromptId(null);
  };

  const loadMoreResponses = () => {
    setResponseVisibleCount((current) => Math.min(current + RESPONSES_BATCH_SIZE, filteredResponses.length));
  };

  const promptsLoading =
    promptsCatalogQuery.isLoading || (promptsCatalogQuery.isFetching && !promptsCatalogQuery.data);

  return {
    mode,
    tab,
    setTab,
    prompts,
    filteredPrompts,
    filteredResponses: visibleResponses,
    filteredResponsesTotal: filteredResponses.length,
    hasMoreResponses: visibleResponses.length < filteredResponses.length,
    loadMoreResponses,
    selectedPrompt,
    selectedResponse,
    selectedPromptIds,
    setSelectedPromptId,
    setSelectedResponseId,
    isPromptDetailsOpen,
    setIsPromptDetailsOpen,
    period,
    setPeriod,
    dateRange,
    setDateRange,
    persona,
    setPersona,
    availablePersonas,
    search,
    setSearch,
    selectedModels,
    availableModels,
    allModelsSelected,
    modelsPopoverOpen,
    setModelsPopoverOpen,
    hasActiveGlobalFilters,
    clearFilters,
    toggleModel,
    promptSort,
    promptSortDirection,
    changePromptSort,
    promptRowMode,
    setPromptRowMode,
    toggleSelectAllPrompts,
    togglePromptSelection,
    applyBulkStatus,
    setFocusPromptId,
    deletePrompt,
    viewMode,
    setViewMode,
    onlyErrors,
    setOnlyErrors,
    criticalOnly,
    setCriticalOnly,
    noMentionOnly,
    setNoMentionOnly,
    topCompetitor,
    setTopCompetitor,
    availableCompetitors,
    isCreateOpen,
    setIsCreateOpen,
    formPrompt,
    setFormPrompt,
    formPersona,
    setFormPersona,
    formModel,
    setFormModel,
    createPrompt,
    addAutoGeneratedPrompts,
    addImportedPrompts,
    getModelVisual,
    promptPage,
    setPromptPage,
    promptTotalItems,
    promptTotalPages,
    canPreviousPromptPage: promptPage > 1,
    canNextPromptPage: promptPage < promptTotalPages,
    promptsLoading,
  };
}
